[
      {
        chapter: 8,
        verse: 1,
        word:1,
        hebrew: "הֲלֹ֣וא",
        english: "Doesn’t",
        strongs: "H3808",
        grammar: "Adverb"
      },
      {chapter: 8,
        verse: 1,
        word:2,
        hebrew: "־",
        english: "wisdom",
        strongs: "H2451",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 1,
        word:3,
        hebrew: "תִקְרָ֣א",
        english: "cry out?",
        strongs: "H7121",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 1,
        word:4,
        hebrew: "וְ֭",
        english: "Doesn’t",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 1,
        word:5,
        hebrew: "־",
        english: "understanding",
        strongs: "H998",
        grammar: "Noun"
      },
      {chapter:8,
        verse: 1,
        word:6,
        hebrew: "תִּשָּׂ֑א",
        english: "raise her voice?",
        strongs: "H5375",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse:2 ,
        word:1 ,
        hebrew: "בְּרֹ֣אשׁ־",
        english: "On the top of",
        strongs: "H7218",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse:2 ,
        word:2 ,
        hebrew: "בָ֭מֹות",
        english: "high places",
        strongs: "H1116",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse:2 ,
        word:3 ,
        hebrew: "עַֽל־",
        english: "by the way,",
        strongs: "H5921",
        grammar: "Preposition"
      },
      {
        chapter: 8,
        verse:2 ,
        word:4 ,
        hebrew: "נְֽתִיבֹ֑ות",
        english: "where the paths",
        strongs: "H5410",
        grammar: "Noun"
      },
      {
      
       chapter: 8,
        verse: 2,
        word: 5,
        hebrew: "נִצָּבָֽה",
        english: "meet,",
        strongs: "H5324",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 3,
        word:1,
        hebrew: "עַ֣ל",
        english: "Beside",
        strongs: "H5921",
        grammar: "Preposition"
      },
      {
        chapter: 8,
        verse: 3,
        word:2 ,
        hebrew: "שְׁעָרִ֣ים",
        english: "the gates,",
        strongs: "H8179",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 3,
        word: 3,
        hebrew: "פֶּֽתַח־",
        english: "at the entry",
        strongs: "H6607",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 3,
        word: 4,
        hebrew: "עִירֹ֑ות",
        english: "of the city,",
        strongs: "H5892",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 3,
        word: 5,
        hebrew: "פֶּ֣תַח",
        english: "at the entry",
        strongs: "H6607",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 3,
        word: 6,
        hebrew: "דָּלִֽים",
        english: "doors,",
        strongs: "H1817",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 3,
        word: 7,
        hebrew: "תִּקְרָ֥א",
        english: "she cries aloud:",
        strongs: "H7121",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 4,
        word: 1,
        hebrew: "אֲלֵיכֶ֣ם",
        english: "I call to you",
        strongs: "H413",
        grammar: "Preposition"
      },
      {
        chapter: 8,
        verse: 4,
        word:2 ,
        hebrew: "אַנְשִׁ֑ים",
        english: "men!",
        strongs: "H582",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 4,
        word: 3,
        hebrew: "וּ֝לְבְנֵ֗י",
        english: "I send my voice",
        strongs: "H1121",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 4,
        word:5 ,
        hebrew: "אָדָֽם׃",
        english: "to the sons of mankind.",
        strongs: "H120",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 5,
        word:1 ,
        hebrew: "פְּתַיִם֮",
        english: "You simple,",
        strongs: "H6612",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 5,
        word: 2,
        hebrew: "הָבִ֪ינוּ",
        english: "understand",
        strongs: "H995",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 5,
        word:3 ,
        hebrew: "עָ֫רְמָ֥ה",
        english: "prudence!",
        strongs: "H6195",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 5,
        word: 4,
        hebrew: "וּכְסִלִּ֡ים",
        english: "You fools,",
        strongs: "H3684",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 5,
        word: 5,
        hebrew: "הָ֘בִ֤ינוּ",
        english: "be of",
        strongs: "H995",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 5,
        word:6 ,
        hebrew: "לֵּ֖ב",
        english: "an understanding",
        strongs: "H3820",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse:5 ,
        word: 7,
        hebrew: "וּֽבְנֵ֣ה",
        english: "heart!",
        strongs: "H1121",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 6,
        word: 1,
        hebrew: "קֹ֭ול",
        english: "Hear,",
        strongs: "H6963",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 6,
        word:2,
        
    
        hebrew: "כִּ֥י",
        english: "for",
        strongs: "H3588",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 6,
        word:3,
        hebrew: "אַמִּ֣ים",
        english: "I will speak",
        strongs: "H5869",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 6,
        word: 4,
        hebrew: "פְלָאִ֑ים",
        english: "excellent things.",
        strongs: "H6381",
        grammar: "Adjective"
      },
      {chapter: 8,
        verse: 6,
        word: 5,
        hebrew: "פִּתְח־",
        english: "The opening",
        strongs: "H6607",
        grammar: "Noun"
      },
      { chapter: 8,
        verse: 6,
        word: 6,
        hebrew: "שְׂפָתַ֥י",
        english: "of my lips",
        strongs: "H8193",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 6,
        word: 7,
        hebrew: "יֹֽשְׁרִ֗ים",
        english: "is for right",
        strongs: "H3476",
        grammar: "Adjective"
      },
      {
        chapter: 8,
        verse: 6,
        word: 8,
        hebrew: "מִֽשְׁרֵי־",
        english: "things.",
        strongs: "H4339",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 7,
        word: 1,
        hebrew: "וְ֭",
        english: "For",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 7,
        word: 2,
        hebrew: "פִי",
        english: "my mouth",
        strongs: "H6310",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 7,
        word: 3,
        hebrew: "יֹֽדֵעַ־",
        english: "speaks truth.",
        strongs: "H3045",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 7,
        word: 4,
        hebrew: "תוֹעֲבַ֣ת",
        english: "Wickedness",
        strongs: "H8441",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 7,
        word:5 ,
        hebrew: "שְׂפָתַ֣י",
        english: "is an abomination",
        strongs: "H8193",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 7,
        word: 6,
        hebrew: "יִשְׂנָ֑אָה",
        english: "to my lips.",
        strongs: "H8130",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 8,
        word: 1,
        hebrew: "כֹּֽל",
        english: "All",
        strongs: "H3605",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 8,
        word: 2,
        hebrew: "אִמְרֹ֣ות",
        english: "the words",
        strongs: "H565",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 8,
        word:3 ,
        hebrew: "פִּ֭י",
        english: "of my mouth",
        strongs: "H6310",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 8,
        word: 4,
        hebrew: "בְּצֶ֣דֶק",
        english: "are in righteousness.",
        strongs: "H6664",
        grammar: "Noun"
      },
      { chapter: 8,
        verse: 8,
        word:5 ,
        hebrew: "אֵ֣ין",
        english: "There is nothing",
        strongs: "H369",
        grammar: "Adverb"
      },
      {chapter: 8,
        verse: 8,
        word:6 ,
        hebrew: "בָּ֭ם",
        english: "crooked or perverse",
        strongs: "H5791",
        grammar: "Adjective"
      },
      {
        chapter: 8,
        verse: 8,
        word: 7,
        hebrew: "נֶ֣גֶד",
        english: "in them.",
        strongs: "H5048",
        grammar: "Preposition"
      },
      {
        chapter: 8,
        verse: 9,
        word: 1,
        hebrew: "כֹּ֣ל",
        english: "They are all",
        strongs: "H3605",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 9,
        word: 2,
        hebrew: "מֵֽשַׂרְתִּ֑י",
        english: "plain to him",
        strongs: "H5475",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 9,
        word: 3,
        hebrew: "מֵבִ֖ין",
        english: "who understands,",
        strongs: "H995",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 9,
        word: 4,
        hebrew: "וְיָשָׁ֣ר",
        english: "right",
        strongs: "H3477",
        grammar: "Adjective"
      },
      {chapter: 8,
        verse: 9,
        word: 5,
        hebrew: "לְמֹֽצְאֵי־",
        english: "to those who find",
        strongs: "H4672",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 9,
        word:6 ,
        hebrew: "דָֽעַת׃",
        english: "knowledge.",
        strongs: "H1847",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 10,
        word: 1,
        hebrew: "קַח־",
        english: "Receive",
        strongs: "H3947",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 10,
        word: 2,
        hebrew: "מוּסָ֑רִי",
        english: "my instruction",
        strongs: "H4148",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 10,
        word: 3,
        hebrew: "וְאַל־",
        english: "rather than",
        strongs: "H408",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 10,
        word: 4,
        hebrew: "כָּ֥סֶף",
        english: "silver,",
        strongs: "H3701",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 10,
        word: 5,
        hebrew: "וּ",
        english: "knowledge",
        strongs: "H1847",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 10,
        word: 6,
        hebrew: "מִזָּהָֽב־",
        english: "rather than choice",
        strongs: "H2091",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 10,
        word: 7,
        hebrew: "בָּֽרֶכֶת־",
        english: "gold.",
        strongs: "H1200",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 11,
        word: 1,
        hebrew: "כִּ֣י",
        english: "For",
        strongs: "H3588",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 11,
        word: 2,
        hebrew: "טֹ֭ובָה",
        english: "wisdom",
        strongs: "H2451",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 11,
        word: 3,
        hebrew: "מִפְּנִינִ֑ים",
        english: "is better than rubies.",
        strongs: "H6443",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 11,
        word:4 ,
        hebrew: "וְ֝",
        english: "All",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 11,
        word:5 ,
        hebrew: "תַּ֣עֲרֹֽץ",
        english: "the things",
        strongs: "H6187",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 11,
        word: 6,
        hebrew: "לֹֽא־",
        english: "that may be desired",
        strongs: "H3808",
        grammar: "Adverb"
      },
      {chapter: 8,
        verse: 11,
        word:7 ,
        hebrew: "יִ֭שָּׁוּק",
        english: "can’t be compared",
        strongs: "H8252",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 11,
        word: 8,
        hebrew: "בָּֽ֑הּ",
        english: "to it.",
        strongs: "H0",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 12,
        word: 1,
        hebrew: "אֲנִ֣י",
        english: "“I, wisdom,",
        strongs: "H589",
        grammar: "Pronoun"
      },
      {chapter: 8,
        verse: 12,
        word:2 ,
        hebrew: "הַשְׂכֵּ֣ל",
        english: "have made prudence",
        strongs: "H7919",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 12,
        word: 3,
        hebrew: "יֹשְׁבָ֑ה",
        english: "my dwelling.",
        strongs: "H3427",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 12,
        word: 4,
        hebrew: "דַּ֭עַת",
        english: "Find out knowledge",
        strongs: "H1847",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 12,
        word:5 ,
        hebrew: "וּ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {
        chapter: 8,
        verse: 12,
        word:6 ,
        hebrew: "תְבוּנָ֥ה",
        english: "discretion.",
        strongs: "H8394",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 13,
        word:1 ,
        hebrew: "פַּ֤חַד",
        english: "The fear",
        strongs: "H6343",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 13,
        word:2 ,
        hebrew: "יְ֝הוָ֗ה",
        english: "of Yahweh",
        strongs: "H3068",
        grammar: "Proper noun"
      },
      {chapter: 8,
        verse: 13,
        word: 3,
        hebrew: "שְׂנ֣וֹא",
        english: "is to hate",
        strongs: "H8130",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 13,
        word: 4,
        hebrew: "רָֽע׃",
        english: "evil.",
        strongs: "H7451",
        grammar: "Adjective"
      },
      {chapter: 8,
        verse: 13,
        word:5 ,
        hebrew: "גָּ֭אוֹן",
        english: "I hate pride,",
        strongs: "H1347",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 13,
        word: 6,
        hebrew: "וּ",
        english: "arrogance,",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 13,
        word:7 ,
        hebrew: "דֶּ֣רֶךְ",
        english: "the evil way,",
        strongs: "H1870",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 13,
        word: 8,
        hebrew: "וּ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {
        chapter: 8,
        verse: 13,
        word: 9,
        hebrew: "פִּ֣י",
        english: "the perverse mouth.",
        strongs: "H6310",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 14,
        word:1,
        hebrew: "עֵצָ֥ה",
        english: "Counsel",
        strongs: "H6098",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 14,
        word:2,
        hebrew: "וְ֝",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 14,
        word:3,
        hebrew: "תְבוּנָ֗ה",
        english: "sound knowledge",
        strongs: "H8394",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 14,
        word:4,
        hebrew: "לִֽי",
        english: "are mine.",
        strongs: "H0",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 14,
        word:5,
        hebrew: "עֹ֣צָה",
        english: "I have understanding",
        strongs: "H6098",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 14,
        word:6,
        hebrew: "וּ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {
        chapter: 8,
        verse: 14,
        word:7 ,
        hebrew: "תֹּ֥ושִׁיָּֽה׃",
        english: "power.",
        strongs: "H3581",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 15,
        word: 1,
        hebrew: "בִּ֭י",
        english: "By me",
        strongs: "H0",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 15,
        word: 2,
        hebrew: "מְֽלָכִ֑ים",
        english: "kings",
        strongs: "H4428",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 15,
        word: 3,
        hebrew: "יִמְלֹ֥כוּ",
        english: "reign,",
        strongs: "H4427",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 15,
        word: 4,
        hebrew: "וְ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 15,
        word: 5,
        hebrew: "שָׂרִ֥ים",
        english: "princes",
        strongs: "H8269",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 15,
        word: 6,
        hebrew: "יָחִֽיקוּ",
        english: "decree justice.",
        strongs: "H2729",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 16,
        word:1 ,
        hebrew: "בִּֽי",
        english: "By me",
        strongs: "H0",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 16,
        word:2 ,
        hebrew: "רָאשִׁ֥ים",
        english: "princes",
        strongs: "H8269",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 16,
        word:3 ,
        hebrew: "מִֽשְׁפְּטִ֑ים",
        english: "rule,",
        strongs: "H4941",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 16,
        word:4,
        hebrew: "וְ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 16,
        word:5 ,
        hebrew: "נְדִיבִ֥ים",
        english: "nobles,",
        strongs: "H5081",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 16,
        word:6 ,
        hebrew: "כָּל־",
        english: "and all",
        strongs: "H3605",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 16,
        word:7 ,
        hebrew: "שֹׁ֥פְטֵי",
        english: "the righteous rulers",
        strongs: "H8199",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 16,
        word: 8,
        hebrew: "אָֽרֶץ׃",
        english: "of the earth.",
        strongs: "H776",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 17,
        word: 1,
        hebrew: "אֹהֲבַ֣י",
        english: "I love",
        strongs: "H157",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 17,
        word: 2,
        hebrew: "אֹ֭הֲבַי",
        english: "those who love me.",
        strongs: "H157",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 17,
        word:3 ,
        hebrew: "וּ",
        english: "Those",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 17,
        word: 4,
        hebrew: "מְֽחַפְּשַׁ֥י",
        english: "who seek me diligently",
        strongs: "H7836",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 17,
        word: 5,
        hebrew: "יִמְצָֽאוּ־",
        english: "will find me.",
        strongs: "H4672",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 18,
        word: 1,
        hebrew: "עִמִּ֗י",
        english: "With me",
        strongs: "H0",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 18,
        word:2 ,
        hebrew: "עֹֽשֶׁר",
        english: "are riches,",
        strongs: "H6239",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 18,
        word:3 ,
        hebrew: "וְ֝",
        english: "honor,",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 18,
        word:4 ,
        hebrew: "הֹון־",
        english: "enduring wealth,",
        strongs: "H1952",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 18,
        word:5 ,
        hebrew: "וְ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {
        chapter: 8,
        verse: 18,
        word: 6,
        hebrew: "צֶֽדֶק",
        english: "prosperity.",
        strongs: "H6666",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 19,
        word: 1,
        hebrew: "פִּרְיִ֣י",
        english: "My fruit",
        strongs: "H6529",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 19,
        word: 2,
        hebrew: "ט֤וֹב",
        english: "is better than gold,",
        strongs: "H2896",
        grammar: "Adjective"
      },
      {chapter: 8,
        verse: 19,
        word:3 ,
        hebrew: "וּ",
        english: "yes, than",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 19,
        word: 4,
        hebrew: "מִפַּ֣ז",
        english: "fine gold,",
        strongs: "H6337",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 19,
        word:5 ,
        hebrew: "וּ",
        english: "my yield",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 19,
        word:6 ,
        hebrew: "מִכָּ֥סֶף",
        english: "than choice",
        strongs: "H3701",
        grammar: "Noun"
      },
      { 
        chapter: 8,
        verse: 19,
        word: 7,
        hebrew: "חָ֝ר֣וּץ",
        english: "silver.",
        strongs: "H2742",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 20,
        word: 1,
        hebrew: "בְּ",
        english: "I walk",
        strongs: "H0",
        grammar: "Preposition"
      },
      {chapter: 8,
        verse: 20,
        word: 2,
        hebrew: "דֶּ֣רֶךְ",
        english: "in the way",
        strongs: "H1870",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 20,
        word: 3,
        hebrew: "צֶ֭דֶק",
        english: "of righteousness,",
        strongs: "H6664",
        grammar: "Noun"  
      },
      {chapter: 8,
        verse: 20,
        word: 4 ,
        hebrew: "בְּתֹ֣וךְ",
        english: "in the middle of",
        strongs: "H8432",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 20,
        word: 5,
        hebrew: "מַֽעְגְּלֵי־",
        english: "the paths",
        strongs: "H4570",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 20,
        word:6 ,
        hebrew: "מִשְׁפָּ֑ט",
        english: "of justice,",
        strongs: "H4941",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 21,
        word: 1,
        hebrew: "לְ֝",
        english: "that",
        strongs: "H0",
        grammar: "Preposition"
      },
      {chapter: 8,
        verse: 21,
        word: 2,
        hebrew: "הַנֹּ֗ותִים",
        english: "I may give wealth",
        strongs: "H5115",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 21,
        word: 3,
        hebrew: "אֹהֲבַ֥י",
        english: "to those who love me.",
        strongs: "H157",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 21,
        word: 4,
        hebrew: "וּ",
        english: "I fill",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {
        chapter: 8,
        verse: 21,
        word:5 ,
        hebrew: "אֹֽצְרֹתֵיהֶֽם׃",
        english: "their treasuries.",
        strongs: "H214",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 22,
        word: 1,
        hebrew: "יְהוָ֣ה",
        english: "Yahweh",
        strongs: "H3068",
        grammar: "Proper noun"
      },
      {chapter: 8,
        verse: 22,
        word: 2,
        hebrew: "קָ֭נָנִי",
        english: "possessed me",
        strongs: "H7069",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 22,
        word: 3,
        hebrew: "רֵאשִׁ֣ית",
        english: "in the beginning",
        strongs: "H7225",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 22,
        word: 4,
        hebrew: "דַּרְכֹּ֑ו",
        english: "of his work,",
        strongs: "H1870",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 22,
        word:5 ,
        hebrew: "קֶ֖דֶם",
        english: "before",
        strongs: "H6924",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 22,
        word: 6,
        hebrew: "מֵֽעֹולָ֣מִים",
        english: "his deeds",
        strongs: "H5769",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 23,
        word: 1,
        hebrew: "נִֽסַּכְתִּ֥י",
        english: "I was set up",
        strongs: "H5258",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 23,
        word: 2,
        hebrew: "מֵרֹ֣אשׁ",
        english: "from everlasting,",
        strongs: "H7218",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 23,
        word: 3,
        hebrew: "מִקֶּ֣דֶם",
        english: "from the beginning,",
        strongs: "H6924",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 23,
        word: 4,
        hebrew: "אֶ֖רֶץ",
        english: "before the earth",
        strongs: "H776",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 23,
        word:5 ,
        hebrew: "וְ",
        english: "existed.",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {
        chapter: 8,
        verse: 24,
        word:1 ,
        hebrew: "לֹ֣א",
        english: "When there were no",
        strongs: "H3808",
        grammar: "Adverb"
      },
      {chapter: 8,
        verse: 24,
        word:2,
        hebrew: "תֵהָ֑וְֹ",
        english: "depths,",
        strongs: "H8415",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 24,
        word:3,
        hebrew: "חֻקִּ֣ים",
        english: "I was born,",
        strongs: "H2712",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 24,
        word:4,
        hebrew: "בְּ",
        english: "when there were no",
        strongs: "H9002",
        grammar: "Preposition"
      },
      {chapter: 8,
        verse: 24,
        word:5,
        hebrew: "מַעְיָנֹ֣ות",
        english: "springs",
        strongs: "H4599",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 24,
        word: 6,
        hebrew: "רְבָֽה׃",
        english: "abounding with water.",
        strongs: "H7227",
        grammar: "Adjective"
      },
      {
        chapter: 8,
        verse: 25,
        word: 1,
        hebrew: "בְּֽ",
        english: "Before the mountains",
        strongs: "H9002",
        grammar: "Preposition"
      },
      {chapter: 8,
        verse: 25,
        word: 2,
        hebrew: "עֻזֹּ֥ות",
        english: "were settled in place,",
        strongs: "H5797",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 25,
        word:3,
        hebrew: "ה֣וּלֵדְתִּ֑י",
        english: "before the hills,",
        strongs: "H3205",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 25,
        word: 4,
        hebrew: "עֹֽוד",
        english: "I was born;",
        strongs: "H5750",
        grammar: "Adverb"
      },
      {
        chapter: 8,
        verse: 26,
        word: 1,
        hebrew: "לֹ֣א",
        english: "while as yet",
        strongs: "H3808",
        grammar: "Adverb"
      },
      {chapter: 8,
        verse: 26,
        word: 2,
       hebrew: "עָשָׂ֗ה",
        english: "he had not made",
        strongs: "H6213",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 26,
        word: 3,
        hebrew: "אָ֭רֶץ",
        english: "the earth,",
        strongs: "H776",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 26,
        word:4 ,
        hebrew: "וּ",
        english: "nor",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 26,
        word:5 ,
        hebrew: "שָׂדָ֥י",
        english: "the fields,",
        strongs: "H7704",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 26,
        word: 6,
        hebrew: "רֵאשִׁ֣ית",
        lenglish: "nor the beginning",
        strongs: "H7225",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 26,
        word: 7,
        hebrew: "עָפָ֖ר",
        english: "of the dust",
        strongs: "H6083",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 26,
        word: 8,
        hebrew: "אַרְצֹ֣ות",
        english: "of the world.",
        strongs: "H776",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 27,
        word:1 ,
        hebrew: "בְּ֭",
        english: "When he established",
        strongs: "H9002",
        grammar: "Preposition"
      },
      {chapter: 8,
        verse: 27,
        word: 2,
        hebrew: "שָׁמַ֣יִם",
        english: "the heavens,",
        strongs: "H8064",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 27,
        word:3 ,
        hebrew: "שָׁ֑ם",
        english: "I was there.",
        strongs: "H8033",
        grammar: "Adverb"
      },
      {chapter: 8,
        verse: 27,
        word: 4,
        hebrew: "בְּֽ",
        english: "When he set",
        strongs: "H9002",
        grammar: "Preposition"
      },
      {chapter: 8,
        verse: 27,
        word:5 ,
        hebrew: "חֻג־",
        english: "a circle",
        strongs: "H2329",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 27,
        word: 6,
        hebrew: "עַל־",
        english: "on the surface",
        strongs: "H5921",
        grammar: "Preposition"
      },
      {
        chapter: 8,
        verse: 27,
        word:7 ,
        hebrew: "תְּהֹ֖ום",
        english: "of the deep,",
        strongs: "H8415",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 28,
        word: 1,
        hebrew: "חֹק־",
        english: "when he established",
        strongs: "H2710",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 28,
        word: 2,
        hebrew: "עֲנָנִ֣ים",
        english: "the clouds",
        strongs: "H6051",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 28,
        word: 3,
        hebrew: "מָֽעֳלָ֑ם",
        english: "above,",
        strongs: "H4605",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 28,
        word:4 ,
        hebrew: "חֲזִ֣יקוּ",
        english: "when the springs",
        strongs: "H2388",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 28,
        word:5 ,
        hebrew: "תְּהֹומֹ֔ות",
        english: "of the deep",
        strongs: "H8415",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 28,
        word:6 ,
        hebrew: "כִּחַ֖זָּקוּ",
        english: "became strong,",
        strongs: "H2388",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 29,
        word: 1,
        hebrew: "מָֽעַרְזִי",
        english: "when he gave",
        strongs: "H5828",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 29,
        word: 2,
        hebrew: "יָ֣ם",
        english: "to the sea",
        strongs: "H3220",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 29,
        word:3 ,
        hebrew: "אֶ֑ז",
        english: "its boundary,",
        strongs: "H227",
        grammar: "Adverb"
      },
      {chapter: 8,
        verse: 29,
        word: 4,
        hebrew: "וַֽ",
        english: "that the waters",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 29,
        word: 5,
        hebrew: "לֹא־",
        english: "should not violate",
        strongs: "H3808",
        grammar: "Adverb"
      },
      {chapter: 8,
        verse: 29,
        word:6 ,
        hebrew: "יַּֽעֲבֹ֣רוּן",
        english: "his commandment,",
        strongs: "H5674",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 29,
        word:7 ,
        hebrew: "וַיַּ֥כֹּנְנ֖וּ",
        english: "when he marked out",
        strongs: "H3559",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 29,
        word: 8,
        hebrew: "מֹוסְדֵי",
        english: "the foundations",
        strongs: "H4146",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 29,
        word: 9,
        hebrew: "אָֽרֶץ׃",
        english: "of the earth,",
        strongs: "H776",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 30,
        word: 1,
        hebrew: "אָֽז",
        english: "then",
        strongs: "H227",
        grammar: "Adverb"
      },
      {chapter: 8,
        verse: 30,
        word: 2,
        hebrew: "אֶ֣הְיֶֽה",
        english: "I was",
        strongs: "H1961",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 30,
        word:3 ,
        hebrew: "אֹמֵ֗ן",
        english: "the craftsman",
        strongs: "H5461",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 30,
        word:4 ,
        hebrew: "אֶ֭צְלֹו",
        english: "by his side.",
        strongs: "H6734",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 30,
        word:5 ,
        hebrew: "וָֽ",
        english: "I was a delight",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 30,
        word:6 ,
        hebrew: "יֹום־",
        english: "day",
        strongs: "H3117",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 30,
        word: 7,
        hebrew: "יֹ֑ום",
        english: "by day,",
        strongs: "H3117",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 30,
        word: 8,
        hebrew: "שַׂחֵ֖ק",
        english: "always rejoicing",
        strongs: "H7832",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 30,
        word: 9,
        hebrew: "לְ֝פָנָ֗יו",
        english: "before him.",
        strongs: "H6440",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 31,
        word: 1,
        hebrew: "שַׂ֭חֵקַתִּי",
        english: "rejoicing",
        strongs: "H7832",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 31,
        word: 2,
        hebrew: "בְּ",
        english: "in his whole",
        strongs: "H9002",
        grammar: "Preposition"
      },
      {chapter: 8,
        verse: 31,
        word:3 ,
        hebrew: "תֵבֵ֑ל",
        english: "world.",
        strongs: "H8398",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 31,
        word: 4,
        hebrew: "וְֽ",
        english: "My delight",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 31,
        word: 5,
        hebrew: "שַׂ֣חַקְתִּי",
        english: "was with",
        strongs: "H7832",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 31,
        word: 6,
        hebrew: "בְנֵי־",
        english: "the sons of",
        strongs: "H1121",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 31,
        word: 7,
        hebrew: "אָדָֽם׃",
        english: "men.",
        strongs: "H120",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 32,
        word:1 ,
        hebrew: "וְֽ",
        english: "Now therefore,",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 32,
        word:2 ,
        hebrew: "עַתָּה֮",
        english: "my sons,",
        strongs: "H6258",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 32,
        word:3 ,
        hebrew: "שִׁמְעוּ־",
        english: "listen to me,",
        strongs: "H8085",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 32,
        word:4 ,
        hebrew: "בָ֣נִים",
        english: "for blessed",
        strongs: "H1121",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 32,
        word:5 ,
        hebrew: "אַשְׁרֵֽי",
        english: "are those who",
        strongs: "H835",
        grammar: "Adjective"
      },
      {
        chapter: 8,
        verse:32 ,
        word: 6,
        hebrew: "דְּרָכַ֣י",
        english: "keep my ways.",
        strongs: "H1870",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 33,
        word:1 ,
        hebrew: "הַֽ",
        english: "Hear",
        strongs: "H9005",
        grammar: "Article"
      },
      {chapter: 8,
        verse: 33,
        word: 2,
        hebrew: "יַסְרֵ֣י",
        english: "instruction,",
        strongs: "H4148",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 33,
        word: 3,
        hebrew: "וְֽ",
        english: "and be wise.",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 33,
        word:4 ,
        hebrew: "אַל־",
        english: "Don't",
        strongs: "H408",
        grammar: "Adverb"
      },
      {
        chapter: 8,
        verse: 33,
        word: 5,
        hebrew: "תִּמְאָֽס׃",
        english: "refuse it.",
        strongs: "H3988",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 34,
        word: 1,
        hebrew: "אַשְׁרֵ֣י",
        english: "Blessed",
        strongs: "H835",
        grammar: "Adjective"
      },
      {chapter: 8,
        verse: 34,
        word:2 ,
        hebrew: "אָדָ֣ם",
        english: "is the man",
        strongs: "H120",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 34,
        word:3 ,
        hebrew: "שֹׁמֵ֣עַ",
        english: "who hears",
        strongs: "H8085",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 34,
        word: 4,
        hebrew: "אֹותִ֑י",
        english: "me,",
        strongs: "H9001",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 34,
        word:5 ,
        hebrew: "לִשְׁקֹ֣וד",
        english: "watching",
        strongs: "H8245",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 34,
        word: 6,
        hebrew: "לַ֭",
        english: "daily",
        strongs: "H9005",
        grammar: "Preposition"
      },
      {chapter: 8,
        verse: 34,
        word: 7,
        hebrew: "פְּתָחָ֑י",
        english: "at my gates,",
        strongs: "H6607",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 34,
        word: 8,
        hebrew: "שֹׁמֵ֥ר",
        english: "waiting",
        strongs: "H8245",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 34,
        word:9 ,
        hebrew: "אֹֽ֝ותֹותַ֗י",
        english: "at my door posts.",
        strongs: "H4201",
        grammar: "Noun"
      },
      {
        chapter: 8,
        verse: 35,
        word: 1,
        hebrew: "כִּ֤י",
        english: "For",
        strongs: "H3588",
        grammar: "Conjunction"
      },
      {
        chapter: 8,
        verse: 35,
        word: 2,
        hebrew: "מֹצֵ֥א",
        english: "whoever finds",
        strongs: "H4672",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 35,
        word:3 ,
        hebrew: "אֹותִ֑י",
        english: "me",
        strongs: "H9001",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 35,
        word: 4,
        hebrew: "מֹ֝צָ֗א",
        english: "finds",
        strongs: "H4672",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 35,
        word:5 ,
        hebrew: "חַיִּ֥ים",
        english: "life,",
        strongs: "H2416",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 35,
        word: 6,
        hebrew: "וַֽ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 35,
        word:7 ,
        hebrew: "יָפֵ֥ק",
        english: "will obtain",
        strongs: "H3318",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 35,
        word: 8,
        hebrew: "רָצֹ֥ון",
        english: "favor",
        strongs: "H7522",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 35,
        word: 9,
        hebrew: "מֵֽ֝",
        english: "from",
        strongs: "H4480",
        grammar: "Preposition"
      },
      {
        chapter: 8,
        verse: 35,
        word:10 ,
        hebrew: "יְהוָ֗ה׃",
        english: "Yahweh.",
        strongs: "H3068",
        grammar: "Proper Noun"
      },
      {
        chapter: 8,
        verse: 36,
        word: 1,
        hebrew: "וְֽ",
        english: "But",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 8,
        verse: 36,
        word: 2,
        hebrew: "שֹׁ֭ונֵא",
        english: "he who sins",
        strongs: "H8130",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 36,
        word:3 ,
        hebrew: "לִי",
        english: "against me",
        strongs: "H9001",
        grammar: "Proper Noun"
      },
      {chapter: 8,
        verse: 36,
        word: 4,
        hebrew: "יַחֲמֹ֣ס",
        english: "wrongs",
        strongs: "H2554",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 36,
        word: 5,
        hebrew: "נַ֑פְשֹׁ֗ו",
        english: "his own soul.",
        strongs: "H5315",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 36,
        word:6 ,
        hebrew: "כָּל־",
        english: "All those",
        strongs: "H3605",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 36,
        word: 7,
        hebrew: "שֹׂנְאַ֥י",
        english: "who hate",
        strongs: "H8130",
        grammar: "Verb"
      },
      {chapter: 8,
        verse: 36,
        word: 8,
        hebrew: "אֹותִ֑י",
        english: "me",
        strongs: "H9001",
        grammar: "Noun"
      },
      {chapter: 8,
        verse: 36,
        word: 9,
        hebrew: "יֶאֱהָ֥בוּ",
        english: "love",
        strongs: "H157",
        grammar: "Verb"
      },
      {
        chapter: 8,
        verse: 36,
        word:10 ,
        hebrew: "מָֽ֝וֶת׃",
        english: "death.",
        strongs: "H4194",
        grammar: "Noun"
      },
     
]