[

  {
    chapter: 9,
    verse: 1,
    Word: 1 ,
    hebrew: "הֲ֭כָמוֹת",
    english: "Wisdom",
    strongs: "H2451",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 1,
    Word:2  ,
    hebrew: "בָנְתָ֣ה",
    english: "has built",
    strongs: "H1129",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 1,
    Word:3  ,
    hebrew: "בֵיתָ֑הּ",
    english: "her house.",
    strongs: "H1004",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 1,
    Word:  4,
    hebrew: "חָצְבָ֖ה",
    english: "She has carved out",
    strongs: "H2672",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 1,
    Word: 5 ,
    hebrew: "עַמּוּדֶ֣יהָ",
    english: "her seven",
    strongs: "H5982",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 1,
    word:6 ,
    hebrew: "טָבָֽחָהּ׃",
    english: "pillars.",
    strongs: "H2874",
    grammar: "Verb"
  },
  {
    chapter: 9,
    verse: 2,
    word:1 ,
     hebrew: "זִ֭בְחָהּ",
    english: "She has prepared",
    strongs: "H2076",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 2,
    word: 2,
    hebrew: "טָבָ֑ח",
    english: "her meat.",
    strongs: "H2874",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 2,
    word: 3,
    hebrew: "מָ֥סְכָה",
    english: "She has mixed",
    strongs: "H4537",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 2,
    word: 4,
    hebrew: "יָ֝יִ֗ן",
    english: "her wine.",
    strongs: "H3196",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 2,
    word:5 ,
    hebrew: "גַּ֥ם",
    english: "She has also",
    strongs: "H1571",
    grammar: "Adverb"
  },
  {
    chapter: 9,
    verse: 2,
    word: 6,
    hebrew: "סֻּ֝לָּמֶ֗יהָ",
    english: "set her table.",
    strongs: "H7979",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 3,
    word:1 ,
    hebrew: "שָׁלְחָ֣ה",
    english: "She has sent out",
    strongs: "H7971",
    grammar: "Verb"
  },
  {
    chapter: 9,
    verse: 3,
    word:2 ,
    hebrew: "אֲמָתֶ֗יהָ",
    english: "her maidens.",
    strongs: "H519",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 3,
    word:3 ,
    hebrew: "תִּקְרָ֥א",
    english: "She cries",
    strongs: "H7121",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 3,
    word:4 ,
    hebrew: "עַל־",
    english: "from the highest",
    strongs: "H5921",
    grammar: "Preposition"
  },
  {
    chapter: 9,
    verse: 3,
    word: 5,
    hebrew: "רֹאשֵׁ֣י",
    english: "places of the city:",
    strongs: "H7218",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 4,
    word: 1,
    hebrew: "֭מִי",
    english: "Whoever",
    strongs: "H4310",
    grammar: "ProNoun"
  },
  {chapter: 9,
    verse: 4,
    word: 2,
    hebrew: "פֶּ֣תִי",
    english: "is simple,",
    strongs: "H6612",
    grammar: "Adjective"
  },
  {chapter: 9,
    verse: 4,
    word: 3,
    hebrew: "יָסֻ֑ר",
    english: "let him turn",
    strongs: "H5493",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 4,
    word: 4,
    hebrew: "הֲֽ",
    english: "in here!",
    strongs: "H518",
    grammar: "Interrogative"
  },
  {chapter: 9,
    verse: 4,
    word: 5,
    hebrew: "וּ֝",
    english: "As for him who",
    strongs: "H9001",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 4,
    word: 6,
    hebrew: "חֲסַר־",
    english: "is void of",
    strongs: "H2638",
    grammar: "Adjective"
  },
  {chapter: 9,
    verse: 4,
    word: 7,
    hebrew: "לֵ֗ב",
    english: "understanding,",
    strongs: "H3820",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 4,
    word: 8,
    hebrew: "אָ֭מְרָה־",
    english: "she says to him,",
    strongs: "H559",
    grammar: "Verb"
  },
  {
    chapter: 9,
    verse:5 ,
    word:1 ,
    hebrew: "לֹ֣ו",
    english: "Come,",
    strongs: "H413",
    grammar: "ProNoun"
  },
  {chapter: 9,
    verse:5 ,
    word: 2,
    hebrew: "לֶֽחֶם־",
    english: "eat some of",
    strongs: "H3899",
    grammar: "Noun"
  },
  {chapter: 9,
    verse:5 ,
    word: 3,
    hebrew: "מַכְמִ֑ית",
    english: "my bread,",
    strongs: "H4201",
    grammar: "Noun"
  },
  {chapter: 9,
    verse:5 ,
    word:4 ,
    hebrew: "וּ֝",
    english: "Drink some of",
    strongs: "H9001",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse:5 ,
    word: 5,
    hebrew: "שְׁתֵּ֗ה",
    english: "the wine",
    strongs: "H8354",
    grammar: "Verb"
  },
  {
    chapter: 9,
    verse:5 ,
    word: 6,
    hebrew: "עָסָ֥ה",
    english: "which I have mixed!",
    strongs: "H6150",
    grammar: "Verb"
  },
  {
    chapter: 9,
    verse: 6,
    word:1 ,
    hebrew: "֭עַזְבְּ",
    english: "Leave",
    strongs: "H5800",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 6,
    word: 2,
    hebrew: "פְּתָיִ֑ם",
    english: "your simple ways,",
    strongs: "H6612",
    grammar: "Adjective"
  },
  {chapter: 9,
    verse: 6,
    word:3 ,
    hebrew: "וִֽ",
    english: "and",
    strongs: "H9001",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 6,
    word:4 ,
    hebrew: "חַ֥י",
    english: "live.",
    strongs: "H2421",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 6,
    word: 5,
    hebrew: "וּֽ",
    english: "Walk",
    strongs: "H9001",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 6,
    word: 6,
    hebrew: "בְּ",
    english: "in the way",
    strongs: "H9001",
    grammar: "Preposition"
  },
  {
    chapter: 9,
    verse: 6,
    word:7 ,
    hebrew: "דֶ֝֗רֶךְ",
    english: "of understanding.",
    strongs: "H1870",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 7,
    word: 1,
    hebrew: "֭מֽוּסָר",
    english: "One who corrects",
    strongs: "H4148",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 7,
    word: 2,
    hebrew: "לֵ֣ץ",
    english: "a mocker",
    strongs: "H3887",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 7,
    word:3 ,
    hebrew: "יִקַּח־",
    english: "invites",
    strongs: "H3947",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 7,
    word: 4,
    hebrew: "ל֣֭וּז",
    english: "insult.",
    strongs: "H3868",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 7,
    word: 5,
    hebrew: "וְ",
    english: "One who reproves",
    strongs: "H9001",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 7,
    word:6 ,
    hebrew: "אֶת־",
    english: "a wicked man",
    strongs: "H7563",
    grammar: "Preposition"
  },
  {chapter: 9,
    verse: 7,
    word:7 ,
    hebrew: "רָ֑שָׁע",
    english: "invites",
    strongs: "H7563",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 7,
    word:8 ,
    hebrew: "מוּמָ֥ר",
    english: "abuse.",
    strongs: "H3972",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 8,
    word:1 ,
    hebrew: "אַל־",
    english: "Don’t reprove",
    strongs: "H408",
    grammar: "Adverb"
  },
  {chapter: 9,
    verse: 8,
    word:2 ,
    hebrew: "יּוֹכִ֑יחַ",
    english: "a scoffer,",
    strongs: "H3198",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 8,
    word:3 ,
    hebrew: "פֶּן־",
    english: "lest",
    strongs: "H6435",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 8,
    word: 4,
    hebrew: "יִשְׂנָ֥א",
    english: "he hate",
    strongs: "H8130",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 8,
    word:5 ,
    hebrew: "לְ֝ךָ֗",
    english: "you.",
    strongs: "H9001",
    grammar: "ProPronoun"
  },
  {chapter: 9,
    verse: 8,
    word: 6,
    hebrew: "הוֹכֵ֣חַ",
    english: "Reprove",
    strongs: "H3198",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 8,
    word: 7,
    hebrew: "חָ֭כָם",
    english: "a wise person,",
    strongs: "H2450",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 8,
    word: 8,
    hebrew: "וְ֝",
    english: "and",
    strongs: "H9001",
    grammar: "Conjunction"
  },
  {
    chapter: 9,
    verse: 8,
    word: 9,
    hebrew: "יֶּאֱהָ֥בְךָ֗",
    english: "he will love",
    strongs: "H157",
    grammar: "Verb"
  },
  {
    chapter: 9,
    verse:9 ,
    word: 1,
    hebrew: "כָל־",
    english: "Teach",
    strongs: "H3605",
    grammar: "Verb"
  },
  {chapter: 9,
    verse:9 ,
    word: 2,
    hebrew: "צַ֝דִּ֗יק",
    english: "a righteous person,",
    strongs: "H6662",
    grammar: "Adjective"
  },
  {chapter: 9,
    verse:9 ,
    word: 3,
    hebrew: "יֹּ֣וסֶף",
    english: "and he will increase",
    strongs: "H3254",
    grammar: "Verb"
  },
  {chapter: 9,
    verse:9 ,
    word: 4,
    hebrew: "בְּ",
    english: "in",
    strongs: "H9001",
    grammar: "Preposition"
  },
  {
    chapter: 9,
    verse: 9,
    word:5 ,
    hebrew: "דַּ֥עַת",
    english: "learning.",
    strongs: "H1847",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 10,
    word: 1,
    hebrew: "יִרְאַ֣ת",
    english: "The fear",
    strongs: "H3374",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 10,
    word: 2,
    hebrew: "יְהוָ֑ה",
    english: "of Yahweh",
    strongs: "H3068",
    grammar: "ProperNoun"
  },
  {chapter: 9,
    verse: 10,
    word:3 ,
    hebrew: "רֵ֣אשִׁית",
    english: "is the beginning",
    strongs: "H7225",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 10,
    word: 4,
    hebrew: "חָכְמָ֣ה",
    english: "of wisdom.",
    strongs: "H2451",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 10,
    word: 5,
    hebrew: "וְדַ֖עַת",
    english: "The knowledge",
    strongs: "H1847",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 10,
    word: 6,
    hebrew: "קְדֹשִׁ֣ים",
    english: "of the Holy One",
    strongs: "H6918",
    grammar: "Adjective"
  },
  {
    chapter: 9,
    verse: 10,
    word: 7,
    hebrew: "בִּֽינָה׃",
    english: "is understanding.",
    strongs: "H998",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 11,
    word:1 ,
    hebrew: "כִּֽי",
    english: "For by me",
    strongs: "H3588",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 11,
    word:2 ,
    hebrew: "אֹ֭רְךָ֣",
    english: "your days",
    strongs: "H753",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 11,
    word: 3,
    hebrew: "יִרְבּ֣וּ",
    english: "will be multiplied.",
    strongs: "H7235",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 11,
    word: 4,
    hebrew: "שְׁנֵ֣י",
    english: "The years",
    strongs: "H8141",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 11,
    word:5 ,
    hebrew: "חַיִּ֑ים",
    english: "of your life",
    strongs: "H2416",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 11,
    word: 6,
    hebrew: "יוֹסִֽיפוּ׃",
    english: "will be increased.",
    strongs: "H3254",
    grammar: "Verb"
  },
  {
    chapter: 9,
    verse: 12,
    word: 1,
    hebrew: "כִּ֤י",
    english: "If",
    strongs: "H3588",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 12,
    word: 2,
    hebrew: "אַתָּ֣ה",
    english: "you",
    strongs: "H859",
    grammar: "ProPronoun"
  },
  {chapter: 9,
    verse: 12,
    word: 3,
    hebrew: "חָכָ֣ם",
    english: "are wise,",
    strongs: "H2450",
    grammar: "Adjective"
  },
  {chapter: 9,
    verse: 12,
    word: 4,
    hebrew: "לְ֭ךָ",
    english: "for yourself.",
    strongs: "H9001",
    grammar: "ProPronoun"
  },
  {chapter: 9,
    verse: 12,
    word:5 ,
    hebrew: "וְ֝אִם",
    english: "If",
    strongs: "H518",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 12,
    word:6 ,
    hebrew: "לֵ֣ץ",
    english: "you mock,",
    strongs: "H3887",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 12,
    word: 7,
    hebrew: "לְבַדֶּֽ֥ךָ",
    english: "you alone",
    strongs: "H905",
    grammar: "ProPronoun"
  },
  {
    chapter: 9,
    verse: 12,
    word: 8,
    hebrew: "תִשָּֽׂא׃",
    english: "will bear it.",
    strongs: "H5375",
    grammar: "Verb"
  },
  {
    chapter: 9,
    verse: 13,
    word: 1,
    hebrew: "ק֭וֹל",
    english: "The foolish woman",
    strongs: "H6963",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 13,
    word:2 ,
    hebrew: "זוֹעֲקָ֣ה",
    english: "is loud,",
    strongs: "H2199",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 13,
    word:3 ,
    hebrew: "פְתָי֑וֹת",
    english: "undisciplined,",
    strongs: "H6612",
    grammar: "Adjective"
  },
  {chapter: 9,
    verse: 13,
    word: 4,
    hebrew: "וְֽ",
    english: "and",
    strongs: "H9001",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 13,
    word:5 ,
    hebrew: "לֹא־",
    english: "knows",
    strongs: "H3808",
    grammar: "Adverb"
  },
  {
    chapter: 9,
    verse: 13,
    word: 6,
    hebrew: "יָ֝דַ֗ע",
    english: "nothing.",
    strongs: "H3045",
    grammar: "Verb"
  },
  {
    chapter: 9,
    verse: 14,
    word:1 ,
    hebrew: "וְ",
    english: "She sits",
    strongs: "H9001",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 14,
    word: 2,
    hebrew: "יֹֽשֶׁבֶת־",
    english: "at the door",
    strongs: "H3427",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 14,
    word:3 ,
    hebrew: "בֵּיתָ֗הּ",
    english: "of her house,",
    strongs: "H1004",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 14,
    word:4 ,
    hebrew: "עַל־",
    english: "on a seat",
    strongs: "H5921",
    grammar: "Preposition"
  },
  {chapter: 9,
    verse: 14,
    word:5 ,
    hebrew: "מְֽרֹאשֵׁ֥י",
    english: "in the high places",
    strongs: "H7218",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 14,
    word:6 ,
    hebrew: "עָ֑רֶם",
    english: "of the city,",
    strongs: "H5892",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 15,
    word: 1,
    hebrew: "לִקְרֹ֣א",
    english: "to call",
    strongs: "H7121",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 15,
    word: 2,
    hebrew: "אֶת־",
    english: "to those",
    strongs: "H853",
    grammar: "Preposition"
  },
  {chapter: 9,
    verse: 15,
    word:3 ,
    hebrew: "עֹבְרִ֣ים",
    english: "who pass by,",
    strongs: "H5674",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 15,
    word:4 ,
    hebrew: "יְשָׁרִ֣ים",
    english: "who go straight",
    strongs: "H3477",
    grammar: "Verb"
  },
  {
    chapter: 9,
    verse: 15,
    word: 5,
    hebrew: "דְּרָכָ֗יו",
    english: "on their ways,",
    strongs: "H1870",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 16,
    word:1 ,
    hebrew: "מִֽי־",
    english: "Whoever",
    strongs: "H4310",
    grammar: "ProPronoun"
  },
  {chapter: 9,
    verse: 16,
    word:2 ,
    hebrew: "פֶתִּ֣י",
    english: "is simple,",
    strongs: "H6612",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 16,
    word: 3,
    hebrew: "יִ֭סֹּר",
    english: "let him turn",
    strongs: "H5493",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 16,
    word: 4,
    hebrew: "הֵ֣נָּה׃",
    english: "in here.",
    strongs: "H2008",
    grammar: "ProPronoun"
  },
  {chapter: 9,
    verse: 16,
    word:5 ,
    hebrew: "וּלְ",
    english: "As for him",
    strongs: "H9001",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 16,
    word: 6,
    hebrew: "נָב֑וֹן",
    english: "who is void of understanding,",
    strongs: "H5046",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 16,
    word: 7,
    hebrew: "אָמְרָ֥ה־",
    english: "she says",
    strongs: "H559",
    grammar: "Verb"
  },
  {
    chapter: 9,
    verse: 16,
    word: 8,
    hebrew: "לֹ֝֗ו",
    english: "to him.",
    strongs: "H9001",
    grammar: "ProPronoun"
  },
  {
    chapter: 9,
    verse: 17,
    word: 1,
    hebrew: "מַ֣יִם",
    english: "Stolen water",
    strongs: "H4325",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 17,
    word: 2,
    hebrew: "גְּנוּבִ֥ים",
    english: "is sweet.",
    strongs: "H1589",
    grammar: "Adjective"
  },
  {chapter: 9,
    verse: 17,
    word: 3,
    hebrew: "וְ֝",
    english: "Food",
    strongs: "H9001",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 17,
    word: 4,
    hebrew: "לֶ֗חֶם",
    english: "eaten",
    strongs: "H3899",
    grammar: "Noun"
  },
  {chapter: 9,
    verse: 17,
    word: 5,
    hebrew: "סָֽתַר׃",
    english: "in secret",
    strongs: "H5641",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 17,
    word: 6,
    hebrew: "נָעִ֥ים",
    english: "is pleasant.”",
    strongs: "H5273",
    grammar: "Adjective"
  },
  {
    chapter: 9,
    verse: 18,
    word: 1,
    hebrew: "וְ",
    english: "But",
    strongs: "H9001",
    grammar: "Conjunction"
  },
  {chapter: 9,
    verse: 18,
    word: 2,
    hebrew: "לֹֽא־",
    english: "But he doesn’t know",
    strongs: "H3808",
    grammar: "Adverb"
  },
  {chapter: 9,
    verse: 18,
    word: 3,
    hebrew: "יָ֭דַע",
    english: "that the departed spirits",
    strongs: "H3045",
    grammar: "Verb"
  },
  {chapter: 9,
    verse: 18,
    word: 4,
    hebrew: "שָׁ֣ם",
    english: "are there,",
    strongs: "H8033",
    grammar: "Adverb"
  },
  {chapter: 9,
    verse: 18,
    word: 5,
    hebrew: "בִּ֑קְעֵי",
    english: "that her guests",
    strongs: "H1237",
    grammar: "Noun"
  },
  {
    chapter: 9,
    verse: 18,
    word: 6,
    hebrew: "שְׁאֹ֖ול",
    english: "are in the depths",
    strongs: "H7585",
    grammar: "Noun"
  },

]