[
     {
        chapter: 7,
        verse: 1,
        word:1 ,
        hebrew: "בְּנִ֣י",
        english: "My son",
        strongs: "H1121",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 1,
        word:2 ,
        hebrew: "שְׁמַ֭ר",
        english: "keep",
        strongs: "H8104",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 1,
        word: 3,
        hebrew: "אָמְרָ֑י",
        english: "my words",
        strongs: "H561",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 1,
        word:4 ,
        hebrew: "וּֽ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 7,
        verse: 1,
        word: 5,
        hebrew: "מִ֝צְוֹתַ֗י",
        english: "my commandments",
        strongs: "H4687",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 1,
        word:6 ,
        hebrew: "תִּצְפֹּ֥ן",
        english: "Lay up",
        strongs: "H6845",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse: 1,
        word:7 ,
        hebrew: "בְּתֹוכֶֽךָ׃",
        english: "within you",
        strongs: "H8432",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 2,
        word:1 ,
        hebrew: "שְׁמֹ֤ר",
        english: "Keep",
        strongs: "H8104",
        grammar: "Verb"
      },
      { chapter: 7,
        verse: 2,
        word:2 ,
        hebrew: "מִצְוֹתַי֙",
        english: "my commandments",
        strongs: "H4687",
        grammar: "Noun"
      },
      { chapter: 7,
        verse: 2,
        word:3 ,
        hebrew: "וֶֽחְיֵ֑ה",
        english: "and live",
        strongs: "H2421",
        grammar: "Verb"
      },
      { chapter: 7,
        verse: 2,
        word:4 ,
        hebrew: "וְ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      { chapter: 7,
        verse: 2,
        word: 5,
        hebrew: "תּוֹרָתִ֖י",
        english: "my teaching",
        strongs: "H8451",
        grammar: "Noun"
      },
      { chapter: 7,
        verse: 2,
        word: 6,
        hebrew: "כְּ",
        english: "as",
        strongs: "H3644",
        grammar: "Preposition"
      },
      { chapter: 7,
        verse: 2,
        word:7 ,
        hebrew: "אִ֣ישׁוֹן",
        english: "the apple",
        strongs: "H380",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 2,
        word: 8,
        hebrew: "עֵינֶֽיךָ׃",
        english: "of your eye",
        strongs: "H5869",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 3,
        word: 1,
        hebrew: "קַשְּׁרֵ֥ם",
        english: "Bind them",
        strongs: "H7194",
        grammar: "Verb"
      },
      {   chapter: 7,
        verse: 3,
        word: 2,
        hebrew: "עַל־",
        english: "on",
        strongs: "H5921",
        grammar: "Preposition"
      },
      {   chapter: 7,
        verse: 3,
        word: 3,
        hebrew: "אֶצְבְּעֹתֶ֑יךָ",
        english: "your fingers",
        strongs: "H676",
        grammar: "Noun"
      },
      {   chapter: 7,
        verse: 3,
        word: 4,
        hebrew: "כָּתְבֵ֖ם",
        english: "Write them",
        strongs: "H3789",
        grammar: "Verb"
      },
      {   chapter: 7,
        verse: 3,
        word: 5,
        hebrew: "עַל־",
        english: "on",
        strongs: "H5921",
        grammar: "Preposition"
      },
      {   chapter: 7,
        verse: 3,
        word:6 ,
        hebrew: "לוּחַ֣",
        english: "the tablet",
        strongs: "H3871",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 3,
        word:7 ,
        hebrew: "לִבְּךָֽ׃",
        english: "of your heart",
        strongs: "H3824",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 4,
        word:1 ,
        hebrew: "אֱמֹ֣ר",
        english: "Tell",
        strongs: "H559",
        grammar: "Verb"
      },
      { chapter: 7,
        verse: 4,
        word:2 ,
        hebrew: "־",
        english: "wisdom,",
        strongs: "H2454",
        grammar: "Noun"
      },
      { chapter: 7,
        verse: 4,
        word:3 ,
        hebrew: "אֲחֹ֑ותִי",
        english: "“You are my sister.",
        strongs: "H269",
        grammar: "Noun"
      },
      { chapter: 7,
        verse: 4,
        word:4 ,
        hebrew: "וּ",
        english: "Call",
        strongs: "H7121",
        grammar: "Conjunction"
      },
      { chapter: 7,
        verse: 4,
        word: 5,
        hebrew: "בִּינָֽה",
        english: "understanding",
        strongs: "H998",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 4,
        word:6 ,
        hebrew: "קְרֹובָ֥ה",
        english: "your relative",
        strongs: "H7138",
        grammar: "Adjective"
      },
      {
        chapter: 7,
        verse: 5,
        word:1 ,
        hebrew: "לָֽךְ׃",
        english: "that they may keep you",
        strongs: "H0",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 5,
        word:2 ,
        hebrew: "מֵֽ",
        english: "from",
        strongs: "H0",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse: 5,
        word:3 ,
        hebrew: "אִשָּׁ֣ה",
        english: "the strange woman,",
        strongs: "H802",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 5,
        word:4 ,
        hebrew: "מִ֭זָּרָה",
        english: "from the foreigner",
        strongs: "H5237",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 5,
        word: 5,
        hebrew: "חֹלֶ֣קֶת",
        english: "who flatters",
        strongs: "H2513",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse: 5,
        word:6 ,
        hebrew: "בִּדְבָרֶ֑יהָ׃",
        english: "with her words.",
        strongs: "H1697",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 6,
        word:1 ,
        hebrew: "כִּ֤י",
        english: "For",
        strongs: "H3588",
        grammar: "Conjunction"
      },
      {chapter: 7,
        verse: 6,
        word:2 ,
        hebrew: "בְּחַלּ֣וֹן",
        english: "at the window",
        strongs: "H2474",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 6,
        word: 3,
        hebrew: "בֵיתִ֑י",
        english: "of my house,",
        strongs: "H1004",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 6,
        word: 4,
        hebrew: "בְּחַ֖לְּכִי",
        english: "I looked out",
        strongs: "H2443",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 6,
        word: 5,
        hebrew: "בְּעַֽד־",
        english: "through",
        strongs: "H1157",
        grammar: "Preposition"
      },
      {
        chapter: 7,
        verse: 6,
        word:6 ,
        hebrew: "אֲשֻׁפִּ֣י",
        english: "my lattice.",
        strongs: "H7199",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 7,
        word: 1,
        hebrew: "וָֽאֶרְאֶ֣ה",
        english: "I saw",
        strongs: "H7200",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 7,
        word:2 ,
        hebrew: "בַפְּתָאִ֣ים",
        english: "among the simple ones.",
        strongs: "H6612",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 7,
        word:3 ,
    
         hebrew: "אֶת־",
        english: "I discerned",
        strongs: "H853",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse: 7,
        word:4 ,
        hebrew: "בַּחוּרִ֗ים",
        english: "among the youths",
        strongs: "H970",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 7,
        word: 5,
        hebrew: "נָ֣עַר",
        english: "a young man",
        strongs: "H5288",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 7,
        word: 6,
        hebrew: "חֲסַר־",
        english: "void of",
        strongs: "H2638",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse:7 ,
        word: 7,
        hebrew: "לֵ֑ב",
        english: "understanding,",
        strongs: "H3820",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 8,
        word:1 ,
        hebrew: "עֹבֵ֥ר",
        english: "passing through",
        strongs: "H5674",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 8,
        word:2 ,
        hebrew: "בְּ֝רֹ֗חַב",
        english: "the street",
        strongs: "H7339",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 8,
        word: 3,
        hebrew: "עַֽל־",
        english: "near",
        strongs: "H5921",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse: 8,
        word: 4,
        hebrew: "פִּנַּת־",
        english: "her corner,",
        strongs: "H6438",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 8,
        word: 5,
        hebrew: "וְֽ",
        english: "he went",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 7,
        verse: 8,
        word:6 ,
        hebrew: "דֶּ֥רֶךְ",
        english: "the way",
        strongs: "H1870",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 8,
        word: 7,
        hebrew: "בֵּֽיתָ֑הּ",
        english: "to her house,",
        strongs: "H1004",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 9,
        word: 1,
        hebrew: "בֵּ֣ין",
        english: "in the twilight,",
        strongs: "H996",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse: 9,
        word:2 ,
        hebrew: "עַ֭רֶב",
        english: "in the evening",
        strongs: "H6153",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 9,
        word: 3,
        hebrew: "יֹ֣ום",
        english: "of the day,",
        strongs: "H3117",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 9,
        word:4 ,
        hebrew: "בִּ֥ין",
        english: "in the middle",
        strongs: "H996",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse: 9,
        word: 5,
        hebrew: "לַ֝֗יְלָה",
        english: "of the night",
        strongs: "H3915",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 9,
        word: 6,
        hebrew: "בְּ",
        english: "and in",
        strongs: "H996",
        grammar: "Preposition"
      },
      {
        chapter: 7,
        verse: 9,
        word: 7,
        hebrew: "אִפְלֵי־",
        english: "the darkness.",
        strongs: "H652",
        grammar: "Adjective"
      },
      {
        chapter: 7,
        verse: 10,
        word: 1,
        hebrew: "וְ",
        english: "Behold, there",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      { chapter: 7,
        verse: 10,
        word: 2,
        hebrew: "אִשָּׁ֥ה",
        english: "a woman",
        strongs: "H802",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 10,
        word: 3,
        hebrew: "לִקְרַאת־",
        english: "met him with",
        strongs: "H7125",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 10,
        word: 4,
        hebrew: "שִׂמְלַ֣ת",
        english: "the attire",
        strongs: "H8071",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 10,
        word: 5,
        hebrew: "זֹונָ֑ה",
        english: "of a prostitute,",
        strongs: "H2181",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 10,
        word: 6,
        hebrew: "וּ",
        english: "and with",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {
        chapter: 7,
        verse: 10,
        word: 7,
        hebrew: "עָקֵֽלֶת׃",
        english: "crafty intent.",
        strongs: "H6128",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse:11 ,
        word: 1,
        hebrew: "רְֽמִיָּ֣ה",
        english: "She is loud",
        strongs: "H7411",
        grammar: "Verb"
      },
      {chapter: 7,
        verse:11 ,
        word: 2,
        hebrew: "וּ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 7,
        verse:11 ,
        word:3 ,
        hebrew: "סְרָרָ֣ה",
        english: "and defiant.",
        strongs: "H5637",
        grammar: "Verb"
      },
      {chapter: 7,
        verse:11 ,
        word:4 ,
        hebrew: "בְּ",
        english: "Her feet",
        strongs: "H9001",
        grammar: "Preposition"
      },
      {
        chapter: 7,
        verse: 11,
        word:5 ,
        hebrew: "בֵיתָֽהּ׃",
        english: "don't stay in her house.",
        strongs: "H1004",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 12,
        word: 1,
        hebrew: "וְֽ",
        english: "Now",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      { chapter: 7,
        verse: 12,
        word: 2,
        hebrew: "הִ֭יא",
        english: "she",
        strongs: "H1931",
        grammar: "Pronoun"
      },
      { chapter: 7,
        verse: 12,
        word: 3,
        hebrew: "בְּ",
        english: "is in",
        strongs: "H9001",
        grammar: "Preposition"
      },
      { chapter: 7,
        verse: 12,
        word: 4,
        hebrew: "רְחֹבֹ֣ות",
        english: "the streets,",
        strongs: "H7339",
        grammar: "Noun"
      },
      { chapter: 7,
        verse: 12,
        word: 5,
        hebrew: "עַתָּ֑ה",
        english: "now",
        strongs: "H6258",
        grammar: "Adverb"
      },
      { chapter: 7,
        verse: 12,
        word: 6,
        hebrew: "בִּרְחֹבֹ֖ות",
        english: "in the squares,",
        strongs: "H7339",
        grammar: "Noun"
      },
      { chapter: 7,
        verse: 12,
        word: 7,
        hebrew: "וַֽ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      { chapter: 7,
        verse: 12,
        word: 8,
        hebrew: "עַ֣ל",
        english: "lurking at",
        strongs: "H5921",
        grammar: "Preposition"
      },
      { chapter: 7,
        verse: 12,
        word: 9,
        hebrew: "כֹּ֑ל",
        english: "every",
        strongs: "H3605",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 12,
        word: 10,
        hebrew: "פִּנָּֽה׃",
        english: "corner.",
        strongs: "H6438",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 13,
        word: 1,
        hebrew: "וַֽ",
        english: "So",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 7,
        verse: 13,
        word: 2,
        hebrew: "תִּפְגְּעֵ֣הוּ",
        english: "she caught him,",
        strongs: "H6293",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 13,
        word: 3,
        hebrew: "וְ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 7,
        verse: 13,
        word: 4,
        hebrew: "נָ֤שַׁק",
        english: "kissed him.",
        strongs: "H5401",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 13,
        word: 5,
        hebrew: "לֹ֣א",
        english: "With an",
        strongs: "H3808",
        grammar: "Adverb"
      },
      {chapter: 7,
        verse: 13,
        word: 6,
        hebrew: "פָנִ֑ים",
        english: "impudent",
        strongs: "H6440",
        grammar: "Adjective"
      },
      {
        chapter: 7,
        verse: 13,
        word: 7,
        hebrew: "אָֽמְרָ֥ה",
        english: "she said to him:",
        strongs: "H559",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse:14 ,
        word:1 ,
        hebrew: "זִבְחֵי־",
        english: "“Sacrifices of",
        strongs: "H2077",
        grammar: "Noun"
      },
      {chapter: 7,
        verse:14 ,
        word:2 ,
        hebrew: "שְׁלָמִ֗ים",
        english: "peace offerings",
        strongs: "H8002",
        grammar: "Noun"
      },
      {chapter: 7,
        verse:14 ,
        word:3 ,
        hebrew: "עִמָּדִ֥י",
        english: "are with me.",
        strongs: "H5978",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse:14 ,
        word:4 ,
        hebrew: "הַיֹּ֣ום",
        english: "Today",
        strongs: "H3117",
        grammar: "Noun"
      },
      {chapter: 7,
        verse:14 ,
        word:5 ,
        Hebrew: "שִׁלְמֹי֙",
      
        english: "I have paid",
        strongs: "H7999",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse: 14,
        word: 6,
        hebrew: "נְדָרָ֔י",
        english: "my vows.",
        strongs: "H5088",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse:15 ,
        word:1 ,
        hebrew: "עַל־כֵּ֥ן",
        english: "Therefore",
        strongs: "H3651",
        grammar: "Conjunction"
      },
      {chapter: 7,
        verse:15 ,
        word:2 ,
        hebrew: "יָצָֽאתִי֙",
        english: "I came out",
        strongs: "H3318",
        grammar: "Verb"
      },
      {chapter: 7,
        verse:15 ,
        word:3 ,
        hebrew: "לִקְרָאתֶ֔ךָ",
        english: "to meet you,",
        strongs: "H7125",
        grammar: "Verb"
      },
      {chapter: 7,
        verse:15 ,
        word:4 ,
        hebrew: "דְּרֹשִׁ֣ים",
        english: "to diligently seek",
        strongs: "H1875",
        grammar: "Verb"
      },
      {chapter: 7,
        verse:15 ,
        word:5 ,
        hebrew: "אֶת־פָּנֶ֑יךָ",
        english: "your face,",
        strongs: "H6440",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 15,
        word:6 ,
        hebrew: "וּמָֽצָֽאתִֽיךָ׃",
        english: "and I have found you.",
        strongs: "H4672",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse: 16,
        word: 1,
        hebrew: "פָרַ֙שְׂתִּ֙י֙",
        english: "I have spread",
        strongs: "H6566",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 16,
        word: 2,
        hebrew: "שְׁכָבִ֔י",
        english: "my couch",
        strongs: "H4904",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 16,
        word: 3,
        hebrew: "שְׂשֻׂ֖ים",
        english: "with carpets",
        strongs: "H8336",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 16,
        word: 4,
        hebrew: "אֹ֣רְגַנִּ֑ים",
        english: "of tapestry,",
        strongs: "H7549",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 16,
        word: 5,
        hebrew: "מִצְרַ֖יִם",
        english: "with striped cloths",
        strongs: "H4714",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 16,
        word: 6,
        hebrew: "קָֽטֶף׃",
        english: "of the yarn of Egypt.",
        strongs: "H6993",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse: 17,
        word: 1,
        hebrew: "נִרְדַּ֖פְתִּי",
        english: "I have perfumed",
        strongs: "H7392",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 17,
        word: 2,
        hebrew: "עַרְשִׂ֥י",
        english: "my bed",
        strongs: "H6210",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 17,
        word:3 ,
        hebrew: "מֹ֙ר־",
        english: "with myrrh,",
        strongs: "H4753",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 17,
        word: 4,
        hebrew: "אֲהָלִ֥ים",
        english: "aloes,",
        strongs: "H174",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 17,
        word: 5,
        hebrew: "וְ",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {
        chapter: 7,
        verse: 17,
        word: 6,
        hebrew: "קִנְּמֹֽון׃",
        english: "cinnamon.",
        strongs: "H7076",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse:18 ,
        word: 1,
        hebrew: "לְכָ֗ה",
        english: "Come,",
        strongs: "H1980",
        grammar: "Verb"
      },
      { chapter: 7,
        verse:18 ,
        word: 2,
        hebrew: "נִ֭שְׁבְּעָה",
        english: "let’s take",
        strongs: "H7650",
        grammar: "Verb"
      },
      { chapter: 7,
        verse:18 ,
        word: 3,
        hebrew: "נִ֣שְׂבְּעָ֑ה",
        english: "our fill",
        strongs: "H7646",
        grammar: "Verb"
      },
      { chapter: 7,
        verse:18 ,
        word: 4,
        hebrew: "עַד־",
        english: "of loving",
        strongs: "H5704",
        grammar: "Preposition"
      },
      { chapter: 7,
        verse:18 ,
        word:5 ,
        hebrew: "בֹּ֗קֶר",
        english: "until the morning.",
        strongs: "H1242",
        grammar: "Noun"
      },
      { chapter: 7,
        verse:18 ,
        word: 6,
        hebrew: "נִֽתְעַנַּ֥גָּה",
        english: "Let’s solace",
        strongs: "H6026",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse: 18,
        word:7 ,
        hebrew: "בַדֹּ֑ודִים",
        english: "ourselves with loving.",
        strongs: "H1730",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 19,
        word:1 ,
        hebrew: "כִּי־",
        english: "For",
        strongs: "H3588",
        grammar: "Conjunction"
      },
      {chapter: 7,
        verse: 19,
        word:2 ,
        hebrew: "אֵ֚ין",
        english: "my husband",
        strongs: "H369",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 19,
        word: 3,
        hebrew: "אֵינֶ֣נּוּ",
        english: "isn’t at",
        strongs: "H369",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 19,
        word: 4,
        hebrew: "בָּ֭יִת",
        english: "home.",
        strongs: "H1004",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 19,
        word: 5,
        hebrew: "הֹ֣לַךְ",
        english: "He has gone",
        strongs: "H1980",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse: 19,
        word:6 ,
        hebrew: "בַּדֶּ֑רֶךְ",
        english: "on a long journey.",
        strongs: "H1870",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 20,
        word:1 ,
        hebrew: "צְרִיחַ",
        english: "He has taken",
        strongs: "H6728",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 20,
        word: 2,
        hebrew: "כֶּ֖סֶף",
        english: "a bag of money",
        strongs: "H3701",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 20,
        word:3 ,
        hebrew: "בְּיָדֹ֣ו",
        english: "with him.",
        strongs: "H3027",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 20,
        word: 4,
        hebrew: "לְיֹ֣ום",
        english: "He will come",
        strongs: "H3117",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 20,
        word: 5,
        hebrew: "כָּֽלּוּנָּ֔ה",
        english: "home at the full moon.",
        strongs: "H3619",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 21,
        word:1 ,
        hebrew: "בְּ",
        english: "With persuasive",
        strongs: "H9001",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse: 21,
        word: 2,
        hebrew: "שִׂפְתֵּ֥י",
        english: "words,",
        strongs: "H8193",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 21,
        word:3 ,
        hebrew: "הִשְׁכִּ֖ילָה",
        english: "she led him astray.",
        strongs: "H7919",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 21,
        word: 4,
        hebrew: "בְּֽ",
        english: "With the",
        strongs: "H9001",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse: 21,
        word:5 ,
        hebrew: "חֲלִקּ֣וּת",
        english: "flattering",
        strongs: "H2519",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 21,
        word:6 ,
        hebrew: "שְׂפָתֶ֑יהָ",
        english: "of her lips,",
        strongs: "H8193",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 21,
        word: 7,
        hebrew: "יַסֵּ֥הּֽוּ",
        english: "she seduced him.",
        strongs: "H5496",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse: 22,
        word:1 ,
        hebrew: "הָֽלַךְ־",
        english: "He followed her",
        strongs: "H1980",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 22,
        word: 2,
        hebrew: "אַחֲרֶ֑יהָ",
        english: "immediately,",
        strongs: "H310",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 22,
        word: 3,
        hebrew: "כְּ",
        english: "as",
        strongs: "H9001",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse: 22,
        word: 4,
        hebrew: "שׁוֹר֙",
        english: "an ox",
        strongs: "H7794",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 22,
        word: 5,
        hebrew: "יָבֵ֔א",
        english: "goes to the slaughter,",
        strongs: "H935",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 22,
        word:6 ,
        hebrew: "וּכְ",
        english: "as",
        strongs: "H9001",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse: 22,
        word:7 ,
        hebrew: "אֱוִ֥יל",
        english: "a fool",
        strongs: "H3684",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 22,
        word: 8,
        hebrew: "לִ",
        english: "stepping into",
        strongs: "H9001",
        grammar: "Preposition"
      },
      {
        chapter: 7,
        verse: 22,
        word:9 ,
        hebrew: "מֹֽוקְשִׁ֑ים",
        english: "a noose.",
        strongs: "H4170",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse:23 ,
        word: 1,
        hebrew: "עַד־",
        english: "Until",
        strongs: "H5704",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse:23 ,
        word: 2,
        hebrew: "יִּֽבְקַ֞ע",
        english: "an arrow strikes",
        strongs: "H1234",
        grammar: "Verb"
      },
      {chapter: 7,
        verse:23 ,
        word: 3,
        hebrew: "כְּ",
        english: "through his liver,",
        strongs: "H9001",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse:23 ,
        word: 4,
        hebrew: "צִפּ֣וֹר",
        english: "as a bird",
        strongs: "H6833",
        grammar: "Noun"
      },
      {chapter: 7,
        verse:23 ,
        word: 5,
        hebrew: "אֶל־",
        english: "hurries to",
        strongs: "H413",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse:23 ,
        word: 6,
        hebrew: "פַּחַ֗ם",
        english: "the snare,",
        strongs: "H6341",
        grammar: "Noun"
      },
      {chapter: 7,
        verse:23 ,
        word: 7,
        hebrew: "וְ֠",
        english: "and",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 7,
        verse:23 ,
        word: 8,
        hebrew: "לֹֽא־",
        english: "doesn’t know",
        strongs: "H3808",
        grammar: "Adverb"
      },
      {chapter: 7,
        verse:23 ,
        word: 9,
        hebrew: "יֵדַ֨ע",
        english: "that it will cost",
        strongs: "H3045",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse: 23,
        word:10 ,
        hebrew: "כִּֽי־",
        english: "his life.",
        strongs: "H3588",
        grammar: "Conjunction"
      },
      {
        chapter: 7,
        verse: 24,
        word: 1,
        hebrew: "לְּֽ",
        english: "Now",
        strongs: "H9001",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse: 24,
        word: 2,
        hebrew: "בָנִ֣ים",
        english: "therefore, sons,",
        strongs: "H1121",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 24,
        word: 3,
        hebrew: "שִׁמְעוּ־",
        english: "listen to me.",
        strongs: "H8085",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 24,
        word: 4,
        hebrew: "אַל־",
        english: "Pay attention",
        strongs: "H408",
        grammar: "Adverb"
      },
      {chapter: 7,
        verse: 24,
        word: 5,
        hebrew: "תַּטֶּ֣ה",
        english: "to the words",
        strongs: "H518",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse: 24,
        word: 6,
        hebrew: "לְ",
        english: "of my mouth.",
        strongs: "H9001",
        grammar: "Preposition"
      },
      {
        chapter: 7,
        verse: 25,
        word:1 ,
        hebrew: "אַל־",
        english: "Don’t let",
        strongs: "H408",
        grammar: "Adverb"
      },
      {chapter: 7,
        verse: 25,
        word: 2,
        hebrew: "יַטֶּ֣ה",
        english: "your heart",
        strongs: "H518",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 25,
        word: 3,
        hebrew: "אֶל־",
        english: "to her ways.",
        strongs: "H413",
        grammar: "Preposition"
      },
      {chapter: 7,
        verse: 25,
        word:4 ,
        hebrew: "אַל־",
        english: "Don’t go",
        strongs: "H408",
        grammar: "Adverb"
      },
      {chapter: 7,
        verse: 25,
        word:5 ,
        hebrew: "תֵּ֭עָֽי",
        english: "astray",
        strongs: "H8582",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse:25 ,
        word: 6,
        hebrew: "בִּנְתִ֣י",
        english: "in her paths,",
        strongs: "H541",
        grammar: "Noun"
      },
      {
        chapter: 7,
        verse: 26,
        word:1 ,
        hebrew: "כִּ֤י",
        english: "for",
        strongs: "H3588",
        grammar: "Conjunction"
      },
      {chapter: 7,
        verse: 26,
        word: 2,
        hebrew: "רַבִּ֣ים",
        english: "she has thrown",
        strongs: "H7227",
        grammar: "Adjective"
      },
      {chapter: 7,
        verse: 26,
        word: 3,
        hebrew: "חַלְלִ֑ים",
        english: "down many wounded.",
        strongs: "H2491",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 26,
        word:4 ,
        hebrew: "אַֽף־",
        english: "Yes, all",
        strongs: "H637",
        grammar: "Adverb"
      },
      {chapter: 7,
        verse: 26,
        word:5 ,
        hebrew: "־",
        english: "her slain",
        strongs: "H2026",
        grammar: "Verb"
      },
      {
        chapter: 7,
        verse: 26,
        word: 6,
        hebrew: "עָצֻ֥מִים",
        english: "are a mighty army.",
        strongs: "H6109",
        grammar: "Adjective"
      },
      {
        chapter: 7,
        verse: 27,
        word:1 ,
        hebrew: "בֵּיתָ֗הּ",
        english: "Her house",
        strongs: "H1004",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 27,
        word:2 ,
        hebrew: "דַּֽרְכֵי־",
        english: "is the way",
        strongs: "H1870",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 27,
        word:3 ,
 
       hebrew: "שְׁאֹ֑ול",
        english: "to Sheol,",
        strongs: "H7585",
        grammar: "Noun"
      },
      {chapter: 7,
        verse: 27,
        word: 4,
        hebrew: "יֹורֵ֥ד",
        english: "going down",
        strongs: "H3381",
        grammar: "Verb"
      },
      {chapter: 7,
        verse: 27,
        word: 5,
        hebrew: "אֶל־",
        english: "to the rooms",
        strongs: "H413",
        grammar: "Preposition"
      },
      {
        chapter: 7,
        verse:27 ,
        word: 6,
        hebrew: "חֲדָרֵֽי",
        english: "of death.",
        strongs: "H2315",
        grammar: "Noun"
      },
]