[
      {
        chapter: 10,
        verse: 1,
        word: 1,
        hebrew: "מִשְׁלֵ֥י",
        english: "The proverbs",
        strongs: "H4912",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 1,
        word:2 ,
        hebrew: "שְׁלֹמֹ֑ה",
        english: "of Solomon.",
        strongs: "H8010",
        grammar: "Proper Noun"
      },
      {chapter: 10,
        verse: 1,
        word:3 ,
        hebrew: "בֵּ֤ן",
        english: "A wise son",
        strongs: "H1121",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 1,
        word: 4,
        hebrew: "יְשַׂמַּ֣ח",
        english: "makes a glad",
        strongs: "H8055",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 1,
        word:5 ,
        hebrew: "אָ֭ב",
        english: "father;",
        strongs: "H1",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 1,
        word: 6,
        hebrew: "וּ",
        english: "but",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 1,
        word: 7,
        hebrew: "בֵּ֣ן",
        english: "a foolish son",
        strongs: "H1121",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 1,
        word: 8,
        hebrew: "תּוֹגֵֽן׃",
        english: "brings grief",
        strongs: "H3013",
        grammar: "Verb"
      },
      {
        chapter: 10,
        verse: 1,
        word: 9,
        hebrew: "לְאֵ֣ם",
        english: "to his mother.",
        strongs: "H517",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 2,
        word: 1,
        hebrew: "אוֹצְרֵי־",
        english: "Treasures of",
        strongs: "H214",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 2,
        word:2 ,
        hebrew: "רֶ֝֗שַׁע",
        english: "wickedness",
        strongs: "H7562",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 2,
        word: 3,
        hebrew: "לֹ֣א",
        english: "profit",
        strongs: "H3808",
        grammar: "Adverb"
      },
      {chapter: 10,
        verse: 2,
        word:4 ,
        hebrew: "יֹֽועִילֽוּ׃",
        english: "nothing,",
        strongs: "H3276",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 2,
        word: 5,
        hebrew: "וּ",
        english: "but",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 2,
        word:6 ,
        hebrew: "צְדָקָ֥ה",
        english: "righteousness",
        strongs: "H6666",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 2,
        word:7 ,
        hebrew: "תַצִּ֣יל",
        english: "delivers",
        strongs: "H5337",
        grammar: "Verb"
      },
      {
        chapter: 10,
        verse: 2,
        word:8 ,
        hebrew: "מִמָּֽוֶת׃",
        english: "from death.",
        strongs: "H4194",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 3,
        word: 1,
        hebrew: "לֹא־",
        english: "Yahweh will not",
        strongs: "H3808",
        grammar: "Adverb"
      },
      {chapter: 10,
        verse: 3,
        word: 2,
        hebrew: "יַרְעִ֣יב",
        english: "allow",
        strongs: "H7456",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 3,
        word: 3,
        hebrew: "נֶֽפֶשׁ",
        english: "the soul",
        strongs: "H5315",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 3,
        word: 4,
        hebrew: "צַדִּיקִ֑ים",
        english: "of the righteous",
        strongs: "H6662",
        grammar: "Adjective"
      },
      {chapter: 10,
        verse: 3,
        word: 5,
        hebrew: "וְ",
        english: "but",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 3,
        word: 6,
        hebrew: "תֹּותַ֖ע",
        english: "he thrusts away",
        strongs: "H5086",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 3,
        word:7 ,
        hebrew: "תַּאֲוַ֣ת",
        english: "the desire",
        strongs: "H8378",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 3,
        word: 8,
        hebrew: "רְשָׁעִֽים׃",
        english: "of the wicked.",
        strongs: "H7563",
        grammar: "Adjective"
      },
      {
        chapter: 10,
        verse: 4,
        word:1 ,
        hebrew: "נִ֭הְיֶה",
        english: "He becomes",
        strongs: "H1961",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 4,
        word: 2,
        hebrew: "רָ֣שׁ",
        english: "poor",
        strongs: "H7326",
        grammar: "Adjective"
      },
      {chapter: 10,
        verse: 4,
        word: 3,
        hebrew: "עֹשֵׂ֣ה",
        english: "who works",
        strongs: "H6213",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 4,
        word:4 ,
        hebrew: "יָדַ֑יִם",
        english: "with a lazy hand,",
        strongs: "H3027",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 4,
        word:5 ,
        hebrew: "וְ",
        english: "but",
        strongs: "H9001",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 4,
        word: 6,
        hebrew: "יַֽד",
        english: "the hand",
        strongs: "H3027",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 4,
        word: 7,
        hebrew: "חָר֥וּץ",
        english: "of the diligent",
        strongs: "H2742",
        grammar: "Adjective"
      },
      {
        chapter: 10,
        verse: 4,
        word:8 ,
        hebrew: "תְּעַשְּׁרֶֽנָּה׃",
        english: "brings wealth.",
        strongs: "H6238",
        grammar: "Verb"
      },
      {
        chapter: 10,
        verse: 5,
        word: 1,
        hebrew: "הֽוֹאֵ֣ל",
        english: "He who gathers",
        strongs: "H6213",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 5,
        word:2 ,
        hebrew: "בַּקַּ֣יִץ",
        english: "in summer",
        strongs: "H7019",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 5,
        word: 3,
        hebrew: "בֵּ֭ן",
        english: "is a wise son,",
        strongs: "H1121",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 5,
        word:4 ,
        hebrew: "וּ",
        english: "but",
        strongs: "H9002",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 5,
        word: 5,
        hebrew: "נִרְדָּ֣ם",
        english: "he who sleeps",
        strongs: "H7290",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 5,
        word:6 ,
        hebrew: "בַּקָּ֑צִיר",
        english: "during the harvest",
        strongs: "H7105",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 5,
        word: 7,
        hebrew: "בֵּ֥ן",
        english: "is a son",
        strongs: "H1121",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 5,
        word: 8,
        hebrew: "מֵבִֽישׁ׃",
        english: "who causes shame.",
        strongs: "H954",
        grammar: "Verb"
      },
      {
        chapter: 10,
        verse:6 ,
        word:1 ,
        hebrew: "בְּרֹֽאש־",
        english: "Blessings are on the head",
        strongs: "H7218",
        grammar: "Noun"
      },
      {chapter: 10,
        verse:6 ,
        word: 2,
        hebrew: "צַדִּיקִ֑ים",
        english: "of the righteous,",
        strongs: "H6662",
        grammar: "Adjective"
      },
      {chapter: 10,
        verse:6 ,
        word:3 ,
        hebrew: "וּ",
        english: "but",
        strongs: "H9002",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse:6 ,
        word:4 ,
        hebrew: "פִּ֝י",
        english: "violence covers the mouth",
        strongs: "H6310",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 6,
        word:5 ,
        hebrew: "רְשָׁעִֽים׃",
        english: "of the wicked.",
        strongs: "H7563",
        grammar: "Adjective"
      },
      {
        chapter: 10,
        verse: 7,
        word: 1,
        hebrew: "זֵ֤כֶר",
        english: "The memory",
        strongs: "H2143",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 7,
        word:2 ,
        hebrew: "צַדִּיקִ֨ים",
        english: "of the righteous",
        strongs: "H6662",
        grammar: "Adjective"
      },
      {chapter: 10,
        verse: 7,
        word: 3,
        hebrew: "לִבְרָכָ֗ה",
        english: "is blessed,",
        strongs: "H1293",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 7,
        word: 4,
        hebrew: "וְ",
        english: "but",
        strongs: "H9002",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 7,
        word: 5,
        hebrew: "שֵׁם־",
        english: "the name of the wicked",
        strongs: "H8034",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 7,
        word: 6,
        hebrew: "רְשָׁעִ֥ים",
        english: "will rot.",
        strongs: "H7563",
        grammar: "Adjective"
      },
      {
        chapter: 10,
        verse: 8,
        word: 1,
        hebrew: "חָ֭כָם",
        english: "The wise",
        strongs: "H2450",
        grammar: "Adjective"
      },
      {chapter: 10,
        verse: 8,
        word: 2,
        hebrew: "בְּֽ",
        english: "in heart",
        strongs: "H3820",
        grammar: "Preposition"
      },
      {chapter: 10,
        verse: 8,
        word: 3,
        hebrew: "מֹ֣צֵא",
        english: "accept commandments,",
        strongs: "H4672",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 8,
        word:4 ,
        hebrew: "וְ",
        english: "but",
        strongs: "H9002",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 8,
        word: 5,
        hebrew: "לֵ֣ב",
        english: "a chattering fool",
        strongs: "H3820",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 8,
        word:6 ,
        hebrew: "יִ֭פֹּל",
        english: "will fall.",
        strongs: "H5307",
        grammar: "Verb"
      },
      {
        chapter: 10,
        verse: 9,
        word:1 ,
        hebrew: "הֹֽלֵךְ־",
        english: "He who walks",
        strongs: "H1980",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 9,
        word: 2,
        hebrew: "תָּ֭מִים",
        english: "blamelessly",
        strongs: "H8549",
        grammar: "Adjective"
      },
      {chapter: 10,
        verse: 9,
        word:3 ,
        hebrew: "יֵלֵ֣ךְ",
        english: "walks surely,",
        strongs: "H1980",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 9,
        word:4 ,
        hebrew: "וְ",
        english: "but",
        strongs: "H9002",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 9,
        word:5 ,
        hebrew: "עֹ֖קֵשׁ",
        english: "he who perverts",
        strongs: "H6140",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 9,
        word:6 ,
        hebrew: "דְּרָכָ֣יו",
        english: "his ways",
        strongs: "H1870",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 9,
        word:7 ,
        hebrew: "יוּוֹדֵ֑עַ",
        english: "will be found out.",
        strongs: "H3045",
        grammar: "Verb"
      },
      {
        chapter: 10,
        verse: 10,
        word: 1,
        hebrew: "קוֹץ־",
        english: "One who winks",
        strongs: "H7192",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 10,
        word: 2,
        hebrew: "עֵ֣ין",
        english: "with the eye",
        strongs: "H5869",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 10,
        word: 3,
        hebrew: "יוֹצִ֣יק",
        english: "causes sorrow,",
        strongs: "H3322",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 10,
        word: 4,
        hebrew: "וְ",
        english: "but",
        strongs: "H9002",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 10,
        word: 5,
        hebrew: "אֱוִ֣יל",
        english: "a chattering fool",
        strongs: "H191",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 10,
        word: 6,
        hebrew: "יִ֭פֹּל",
        english: "will fall.",
        strongs: "H5307",
        grammar: "Verb"
      },
      {
        chapter: 10,
        verse: 11,
        word: 1,
        hebrew: "מַקְּוֵ֣ה",
        english: "The mouth",
        strongs: "H4726",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 11,
        word:2 ,
        hebrew: "צַדִּיקִ֑ים",
        english: "of the righteous",
        strongs: "H6662",
        grammar: "Adjective"
      },
      {chapter: 10,
        verse: 11,
        word:3 ,
        hebrew: "מַעְיָן־",
        english: "is a spring",
        strongs: "H4599",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 11,
        word:4 ,
        hebrew: "חַיִּ֣ים׃",
        english: "of life,",
        strongs: "H2416",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 11,
        word: 5,
        hebrew: "וּ",
        english: "but",
        strongs: "H9002",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 11,
        word:6 ,
        hebrew: "פִּ֭י",
        english: "violence covers the mouth",
        strongs: "H6310",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 11,
        word: 7,
        hebrew: "רְשָׁעִ֣ים׃",
        english: "of the wicked.",
        strongs: "H7563",
        grammar: "Adjective"
      },
      {
        chapter: 10,
        verse:12 ,
        word: 1,
        hebrew: "שֹׂנֵ֣א",
        english: "Hatred stirs up",
        strongs: "H8130",
        grammar: "Verb"
      },
      {chapter: 10,
        verse:12 ,
        word: 2,
        hebrew: "מָד֑וֹן",
        english: "strife,",
        strongs: "H4066",
        grammar: "Noun"
      },
      {chapter: 10,
        verse:12 ,
        word:3 ,
        hebrew: "וּ",
        english: "but",
        strongs: "H9002",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse:12 ,
        word: 4,
        hebrew: "כָּסָ֖ה",
        english: "love covers",
        strongs: "H3680",
        grammar: "Verb"
      },
      {chapter: 10,
        verse:12 ,
        word:5 ,
        hebrew: "כָל־",
        english: "all",
        strongs: "H3605",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 12,
        word: 6,
        hebrew: "פְּשָׁעִ֣ים׃",
        english: "wrongs.",
        strongs: "H6588",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 13,
        word: 1,
        hebrew: "בְּשִׂפְתֵי־",
        english: "Wisdom is found on the lips",
        strongs: "H8193",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 13,
        word: 2,
        hebrew: "מֵ֭בִין",
        english: "of him who has discernment,",
        strongs: "H995",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 13,
        word:3 ,
        hebrew: "וַֽ",
        english: "but",
        strongs: "H9002",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 13,
        word: 4,
        hebrew: "שֵׁבֶ֥ט",
        english: "a rod",
        strongs: "H7626",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 13,
        word:5 ,
        hebrew: "לְ",
        english: "for the",
        strongs: "H853",
        grammar: "Preposition"
      },
      {chapter: 10,
        verse: 13,
        word: 6,
        hebrew: "גֵּ֣ו",
        english: "back",
        strongs: "H1460",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse:13 ,
        word:7 ,
        hebrew: "נָבֽוֹן׃",
        english: "of him who is void of understanding.",
        strongs: "H5036",
        grammar: "Adjective"
      },
      {
        chapter: 10,
        verse: 14,
        word: 1,
        hebrew: "חַכָּמִ֣ים",
        english: "Wise men",
        strongs: "H2450",
        grammar: "Adjective"
      },
      {chapter: 10,
        verse: 14,
        word: 2,
        hebrew: "יַ֭אֲצִרוּ",
        english: "lay up",
        strongs: "H686",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 14,
        word:3 ,
        hebrew: "דַּ֣עַת",
        english: "knowledge,",
        strongs: "H1847",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 14,
        word: 4,
        hebrew: "וּֽ",
        english: "but",
        strongs: "H9002",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 14,
        word: 5,
        hebrew: "פִּ֖י",
        english: "the mouth",
        strongs: "H6310",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 14,
        word:6 ,
        hebrew: "אֱוִ֣יל",
        english: "of the foolish",
        strongs: "H191",
        grammar: "Adjective"
      },
      {chapter: 10,
        verse: 14,
        word: 7,
        hebrew: "קָר֑וֹב",
        english: "is near",
        strongs: "H7138",
        grammar: "Verb"
      },
      {chapter: 10,
        verse: 14,
        word: 8,
        hebrew: "לְ",
        english: "to",
        strongs: "H901",
        grammar: "Preposition"
      },
      {
        chapter: 10,
        verse: 14,
        word: 9,
        hebrew: "שֹׁ֣חַת",
        english: "ruin.",
        strongs: "H7743",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 15,
        word:1 ,
        hebrew: "עָשִׁ֥יר",
        english: "The rich man’s",
        strongs: "H6223",
        grammar: "Adjective"
      },
      {chapter: 10,
        verse: 15,
        word:2 ,
        hebrew: "רָ֝שְׁוָת֗וֹ",
        english: "wealth",
        strongs: "H7626",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 15,
        word: 3,
        hebrew: "עִֽיר",
        english: "is his strong city.",
        strongs: "H5892",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 15,
        word:4 ,
        hebrew: "ומַחֲרַ֣ב",
        english: "The destruction",
        strongs: "H2723",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 15,
        word: 5,
        hebrew: "עֲנִיִּ֣ים",
        english: "of the poor",
        strongs: "H6041",
        grammar: "Adjective"
      },
      {
        chapter: 10,
        verse: 15,
        word:6 ,
        hebrew: "רִ֭שְׁעָתָם",
        english: "is their poverty.",
        strongs: "H7564",
        grammar: "Noun"
      },
      {
        chapter: 10,
        verse: 16,
        word:1 ,
        hebrew: "עָצֵ֣ב",
        english: "The labor",
        strongs: "H6089",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 16,
        word: 2,
        hebrew: "צַדִּיקִ֑ים",
        english: "of the righteous",
        strongs: "H6662",
        grammar: "Adjective"
      },
      {chapter: 10,
        verse: 16,
        word: 3,
        hebrew: "לְ",
        english: "leads to",
        strongs: "H901",
        grammar: "Preposition"
      },
      {chapter: 10,
        verse: 16,
        word: 4,
        hebrew: "חַ֖יִּים׃",
        english: "life.",
        strongs: "H2416",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 16,
        word:5 ,
        hebrew: "וְ",
        english: "The",
        strongs: "H9002",
        grammar: "Conjunction"
      },
      {chapter: 10,
        verse: 16,
        word:6 ,
        hebrew: "פְּרִ֣י",
        english: "increase",
        strongs: "H8393",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 16,
        word: 7,
        hebrew: "רְשָׁעִ֑",
        english: "of the wicked",
        strongs: "H7563",
         grammar: "Adjective"
      },
        {
          chapter: 10,
          verse: 16,
          word: 8,
          hebrew: "חַטָּ֥את",
          english: "leads to sin.",
          strongs: "H2403",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 17,
          word: 1,
          hebrew: "אֹֽרַח־",
          english: "He is in the way",
          strongs: "H734",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 17,
          word: 2,
          hebrew: "חַ֭יִּים",
          english: "of life",
          strongs: "H2416",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 17,
          word:3 ,
          hebrew: "מֻסַּ֣ר",
          english: "who heeds correction,",
          strongs: "H4148",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 17,
          word:4 ,
          hebrew: "וְ",
          english: "but",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 17,
          word: 5,
          hebrew: "עֹזֵ֥ב",
          english: "he who forsakes",
          strongs: "H5800",
          grammar: "Verb"
        },
        {chapter: 10,
          verse: 17,
          word:6 ,
          hebrew: "תּוֹכָ֗חַת",
          english: "reproof",
          strongs: "H8433",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 17,
          word: 7,
          hebrew: "מַתְעִ֥ית",
          english: "leads others astray.",
          strongs: "H8582",
          grammar: "Verb"
        },
        {
          chapter: 10,
          verse: 18,
          word: 1,
          hebrew: "טַֽמְנָ֖ה",
          english: "He who hides",
          strongs: "H2934",
          grammar: "Verb"
        },
        {chapter: 10,
          verse: 18,
          word: 2,
          hebrew: "שִׂנְאָ֥ה",
          english: "hatred",
          strongs: "H8135",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 18,
          word:3 ,
          hebrew: "שְׂפָתָ֑יו",
          english: "has lying lips.",
          strongs: "H8193",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 18,
          word:4 ,
          hebrew: "וְ",
          english: "He who",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 18,
          word: 5,
          hebrew: "יֹצֵ֣א",
          english: "utters",
          strongs: "H3318",
          grammar: "Verb"
        },
        {chapter: 10,
          verse: 18,
          word:6 ,
          hebrew: "דִבָּ֑ה",
          english: "a slander",
          strongs: "H1681",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 18,
          word: 7,
          hebrew: "כְּסִ֖יל",
          english: "is a fool.",
          strongs: "H3684",
          grammar: "Adjective"
        },
        {
          chapter: 10,
          verse: 19,
          word: 1,
          hebrew: "בְּרֹ֣ב",
          english: "In the multitude",
          strongs: "H7230",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 19,
          word: 2,
          hebrew: "דְּבָרִ֣ים",
          english: "of words",
          strongs: "H1697",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 19,
          word:3 ,
          hebrew: "אֵ֭ין",
          english: "there is no lack of",
          strongs: "H369",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 19,
          word:4 ,
          hebrew: "אָ֑וֶן",
          english: "disobedience,",
          strongs: "H205",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 19,
          word: 5,
          hebrew: "וּ",
          english: "but",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 19,
          word: 6,
          hebrew: "כֹּ֖חַ",
          english: "he who restrains",
          strongs: "H3581",
          grammar: "Verb"
        },
        {chapter: 10,
          verse: 19,
          word: 7,
          hebrew: "שְׂפָתָ֣יו",
          english: "his lips",
          strongs: "H8193",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 19,
          word:8 ,
          hebrew: "מַשְׂכִּ֣יל",
          english: "does wisely.",
          strongs: "H7919",
          grammar: "Verb"
        },
        {
          chapter: 10,
          verse: 20,
          word: 1,
          hebrew: "לָּֽֽשׁוֹן",
          english: "The tongue",
          strongs: "H3956",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 20,
          word:2 ,
          hebrew: "צַדִּיקִ֥ים",
          english: "of the righteous",
          strongs: "H6662",
          grammar: "Adjective"
        },
        {chapter: 10,
          verse: 20,
          word:3 ,
          hebrew: "כֶּֽסֶף־",
          english: "is like choice silver.",
          strongs: "H3701",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 20,
          word: 4,
          hebrew: "לֵֽב",
          english: "The heart",
          strongs: "H3820",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 20,
          word: 5,
          hebrew: "רְשָׁעִ֥ים",
          english: "of the wicked",
          strongs: "H7563",
          grammar: "Adjective"
        },
        {
          chapter: 10,
          verse: 20,
          word: 6,
          hebrew: "מְ֝עַ֗ט",
          english: "is of little worth.",
          strongs: "H4592",
          grammar: "Adjective"
        },
        {
          chapter: 10,
          verse: 21,
          word: 1,
          hebrew: "שְׂפַ֣תֵי",
          english: "The lips",
          strongs: "H8193",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 21,
          word: 2,
          hebrew: "צַדִּיקִ֑ים",
          english: "of the righteous",
          strongs: "H6662",
          grammar: "Adjective"
        },
        {chapter: 10,
          verse: 21,
          word: 3,
          hebrew: "יַֽרְעִ֥יבוּ",
          english: "feed many,",
          strongs: "H7456",
          grammar: "Verb"
        },
        {chapter: 10,
          verse: 21,
          word:4 ,
          hebrew: "וּֽ",
          english: "but",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 21,
          word:5 ,
          hebrew: "כְּסִ֖ילִים",
          english: "the foolish",
          strongs: "H3684",
          grammar: "Adjective"
        },
        {chapter: 10,
          verse: 21,
          word:6 ,
          hebrew: "יָמ֥וּתוּ",
          english: "die",
          strongs: "H4191",
          grammar: "Verb"
        },
        {chapter: 10,
          verse: 21,
          word:7 ,
          hebrew: "בְּ֝אֵ֗ין",
          english: "for lack of",
          strongs: "H369",
          grammar: "Verb"
        },
        {
          chapter: 10,
          verse: 21,
          word:8 ,
          hebrew: "לֵ֥ב",
          english: "understanding.",
          strongs: "H3820",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 22,
          word: 1,
          hebrew: "בִּרְכַּ֣ת",
          english: "Yahweh’s blessing",
          strongs: "H1293",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 22,
          word: 2,
          hebrew: "יְהוָ֗ה",
          english: "brings wealth,",
          strongs: "H3068",
          grammar: "Proper Noun"
        },
        {chapter: 10,
          verse: 22,
          word:3 ,
          hebrew: "וְלֹ֣א",
          english: "and he adds no",
          strongs: "H3808",
          grammar: "Conjunction"
        },
        {
          chapter: 10,
          verse: 22,
          word: 4,
          hebrew: "יָסִֽיף",
          english: "trouble to it.",
          strongs: "H3254",
          grammar: "Verb"
        },
        {
          chapter: 10,
          verse: 23,
          word: 1,
          hebrew: "תּ֥וֹעֲבַת",
          english: "It is a fool’s pleasure",
          strongs: "H8441",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 23,
          word: 2,
          hebrew: "אִוֶּ֑לֶת",
          english: "to do wickedness,",
          strongs: "H200",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 23,
          word:3 ,
          hebrew: "וּֽ",
          english: "but",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 23,
          word:4 ,
          hebrew: "חָכְמָ֥ה",
          english: "wisdom",
          strongs: "H2451",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 23,
          word:5 ,
          hebrew: "אִֽישׁ",
          english: "is a man",
          strongs: "H376",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 23,
          word: 6,
          hebrew: "בִּֽינָה־",
          english: "of understanding’s pleasure.",
          strongs: "H8394",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 24,
          word: 1,
          hebrew: "יִֽירְאַת",
          english: "What the wicked fear",
          strongs: "H3374",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 24,
          word: 2,
          hebrew: "רְשָׁעִ֑ים",
          english: "will overtake them,",
          strongs: "H7563",
          grammar: "Adjective"
        },
        {chapter: 10,
          verse: 24,
          word:3 ,
          hebrew: "וְ",
          english: "but",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 24,
          word:4 ,
          hebrew: "תַאֲוַ֖ת",
          english: "the desire of the righteous",
          strongs: "H8378",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 24,
          word: 5,
          hebrew: "צַדִּיקִ֣ים",
          english: "will be granted.",
          strongs: "H6662",
          grammar: "Adjective"
        },
        {
          chapter: 10,
          verse: 25,
          word:1 ,
          hebrew: "עָב֤וֹר",
          english: "When the whirlwind passes,",
          strongs: "H5674",
          grammar: "Verb"
        },
        {chapter: 10,
          verse: 25,
          word:2 ,
          hebrew: "רָשָׁ֨ע",
          english: "the wicked is no more;",
          strongs: "H7563",
          grammar: "Adjective"
        },
        {chapter: 10,
          verse: 25,
          word: 3,
          hebrew: "וְ",
          english: "but",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 25,
          word: 4,
          hebrew: "צַדִּיקִ֥ים",
          english: "the righteous stand firm",
          strongs: "H6662",
          grammar: "Adjective"
        },
        {
          chapter: 10,
          verse: 25,
          word:5 ,
          hebrew: "עוֹלָ֗ם",
          english: "forever.",
          strongs: "H5769",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 26,
          word:1 ,
          hebrew: "חֹ֥מֶץ",
          english: "As vinegar",
          strongs: "H2558",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 26,
          word: 2,
          hebrew: "לַ",
          english: "to the",
          strongs: "H9013",
          grammar: "Preposition"
        },
        {chapter: 10,
          verse: 26,
          word:3 ,
          hebrew: "שִׁנַּ֑יִם",
          english: "teeth,",
          strongs: "H8127",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 26,
          word:4 ,
          hebrew: "וְ",
          english: "and",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 26,
          word: 5,
          hebrew: "עָשָׁ֖ן",
          english: "as smoke",
          strongs: "H6227",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 26,
          word:6 ,
          hebrew: "לָעֵינָ֣יִם",
          english: "to the eyes,",
          strongs: "H5869",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 26,
          word:7 ,
          hebrew: "כֵּ֚ן",
          english: "so is",
          strongs: "H3651",
          grammar: "Adverb"
        },
        {chapter: 10,
          verse: 26,
          word:8 ,
          hebrew: "הָֽ",
          english: "the",
          strongs: "H9014",
          grammar: "Article"
        },
        {chapter: 10,
          verse: 26,
          word:9 ,
          hebrew: "עַצְלַ֣ת",
          english: "sluggard",
          strongs: "H6102",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 26,
          word:10 ,
          hebrew: "לְ",
          english: "to",
          strongs: "H9013",
          grammar: "Preposition"
        },
        {
          chapter: 10,
          verse: 26,
          word:11 ,
          hebrew: "שָׁלְחָ֔יו",
          english: "those who send him.",
          strongs: "H7971",
          grammar: "Verb"
        },
        {
          chapter: 10,
          verse: 27,
          word: 1,
          hebrew: "יִרְאַ֣ת",
          english: "The fear of",
          strongs: "H3374",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 27,
          word:2 ,
          hebrew: "יְהוָ֑ה",
          english: "Yahweh",
          strongs: "H3068",
          grammar: "Proper Noun"
        },
        {chapter: 10,
          verse: 27,
          word:3 ,
          hebrew: "תַּ֣אֲרִ֔יךְ",
          english: "prolongs days,",
          strongs: "H748",
          grammar: "Verb"
        },
        {chapter: 10,
          verse: 27,
          word:4 ,
          hebrew: "וּ",
          english: "but",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 27,
          word: 5,
          hebrew: "שְׁנוֹת־",
          english: "the years of the wicked",
          strongs: "H8141",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 27,
          word:6 ,
          hebrew: "רְשָׁעִ֥ים",
          english: "shall be shortened.",
          strongs: "H7563",
          grammar: "Adjective"
        },
        {
          chapter: 10,
          verse: 28,
          word:1 ,
          hebrew: "תִּקְוַת־",
          english: "The prospect of",
          strongs: "H8615",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 28,
          word: 2,
          hebrew: "צַדִּיקִ֑ים",
          english: "the righteous",
          strongs: "H6662",
          grammar: "Adjective"
        },
        {chapter: 10,
          verse: 28,
          word: 3,
          hebrew: "שִׂמְחָ֥ה",
          english: "is joy,",
          strongs: "H8057",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 28,
          word:4 ,
          hebrew: "וְ",
          english: "but",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 28,
          word: 5,
          hebrew: "תִקְוַ֥ת",
          english: "the hope of",
          strongs: "H8615",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 28,
          word:6 ,
          hebrew: "רְשָׁעִֽים",
          english: "the wicked",
          strongs: "H7563",
          grammar: "Adjective"
        },
        {
          chapter: 10,
          verse: 28,
          word: 7,
          hebrew: "תֹאבֵֽד׃",
          english: "will perish.",
          strongs: "H6",
          grammar: "Verb"
        },
        {
  
          chapter: 10,
          verse: 29,
          word:1 ,
          hebrew: "דֶּ֣רֶךְ",
          english: "The way of",
          strongs: "H1870",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 29,
          word: 2,
          hebrew: "יְהוָ֔ה",
          english: "Yahweh",
          strongs: "H3068",
          grammar: "Proper Noun"
        },
        {chapter: 10,
          verse: 29,
          word:3 ,
          hebrew: "מָֽצְרָ֥ה",
          english: "is a stronghold",
          strongs: "H4686",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 29,
          word: 4,
          hebrew: "לַ",
          english: "to the",
          strongs: "H9013",
          grammar: "Preposition"
        },
        {chapter: 10,
          verse: 29,
          word:5 ,
          hebrew: "תָּ֑ם",
          english: "upright,",
          strongs: "H8535",
          grammar: "Adjective"
        },
        {chapter: 10,
          verse: 29,
          word:6 ,
          hebrew: "וּ",
          english: "but",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 29,
          word: 7,
          hebrew: "מַ֝חֲתָ֗ה",
          english: "it is a destruction",
          strongs: "H4288",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 29,
          word:8 ,
          hebrew: "לְ",
          english: "to",
          strongs: "H9013",
          grammar: "Preposition"
        },
        {chapter: 10,
          verse: 29,
          word: 9,
          hebrew: "פֹּ֥עֲלֵי",
          english: "the workers",
          strongs: "H6466",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 29,
          word: 10,
          hebrew: "אָֽוֶן׃",
          english: "of iniquity.",
          strongs: "H205",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 30,
          word:1 ,
          hebrew: "צַדִּיקִ֑ים",
          english: "The righteous",
          strongs: "H6662",
          grammar: "Adjective"
        },
        {chapter: 10,
          verse: 30,
          word: 2,
          hebrew: "לְ",
          english: "will never",
          strongs: "H3808",
          grammar: "Preposition"
        },
        {chapter: 10,
          verse: 30,
          word:3 ,
          hebrew: "נוּץ־",
          english: "be removed,",
          strongs: "H5253",
          grammar: "Verb"
        },
        {chapter: 10,
          verse: 30,
          word:4 ,
          hebrew: "וְ",
          english: "but",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 30,
          word: 5,
          hebrew: "רְשָׁעִ֖ים",
          english: "the wicked",
          strongs: "H7563",
          grammar: "Adjective"
        },
        {chapter: 10,
          verse: 30,
          word:6 ,
          hebrew: "לֹ֣א",
          english: "will not",
          strongs: "H3808",
          grammar: "Preposition"
        },
        {chapter: 10,
          verse: 30,
          word: 7,
          hebrew: "יִשְׁכְּנ֥וּ",
          english: "dwell",
          strongs: "H7931",
          grammar: "Verb"
        },
        {
          chapter: 10,
          verse: 30,
          word: 8,
          hebrew: "בָאָֽרֶץ׃",
          english: "in the land.",
          strongs: "H776",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 31,
          word: 1,
          hebrew: "פִּֽי־",
          english: "The mouth of",
          strongs: "H6310",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 31,
          word: 2,
          hebrew: "צַדִּיקִ֗ים",
          english: "the righteous",
          strongs: "H6662",
          grammar: "Adjective"
        },
        {chapter: 10,
          verse: 31,
          word: 3,
          hebrew: "יָפִ֥יק",
          english: "produces",
          strongs: "H3318",
          grammar: "Verb"
        },
        {chapter: 10,
          verse: 31,
          word:4 ,
          hebrew: "חָכְמָ֑ה",
          english: "wisdom,",
          strongs: "H2451",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 31,
          word:5 ,
          hebrew: "וּ",
          english: "but",
          strongs: "H9002",
          grammar: "Conjunction"
        },
        {chapter: 10,
          verse: 31,
          word:6 ,
          hebrew: "לְשׁוֹנ־",
          english: "the perverse tongue",
          strongs: "H8416",
          grammar: "Noun"
        },
        {
          chapter: 10,
          verse: 31,
          word: 7,
          hebrew: "תִכָּֽרֵת׃",
          english: "will be cut off.",
          strongs: "H3772",
          grammar: "Verb"
        },
        {
          chapter: 10,
          verse: 32,
          word: 1,
          hebrew: "שִׂפְתֵי־",
          english: "The lips of",
          strongs: "H8193",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 32,
          word: 2,
          hebrew: "צַדִּיקִ֥ים",
          english: "the righteous",
          strongs: "H6662",
          grammar: "Adjective"
        },
        {chapter: 10,
          verse: 32,
          word: 3,
          hebrew: "יָדְע֖וּ",
          english: "know",
          strongs: "H3045",
          grammar: "Verb"
        },
        {chapter: 10,
          verse: 32,
          word: 4,
          hebrew: "רָ֑צוֹן",
          english: "what is acceptable,",
          strongs: "H7522",
          grammar: "Noun"
        },
        {chapter: 10,
          verse: 32,
          word: 5,
          hebrew: "וּ",
          english: "but",
          strongs: "H9002",
          grammar: "Conjunction"
        },
     
      {chapter: 10,
        verse: 32,
        word: 6,
        hebrew: "פֶ֥ה",
        english: "the mouth",
        strongs: "H6310",
        grammar: "Noun"
      },
      {chapter: 10,
        verse: 32,
        word: 7,
        hebrew: "רְשָׁעִ֗ים",
        english: "of the wicked",
        strongs: "H7563",
        grammar: "Adjective"
      },
      {
        chapter: 10,
        verse: 32,
        word:8 ,
        hebrew: "עִקֵּ֥שׁ",
        english: "is perverse.",
        strongs: "H6143",
        grammar: "Adjective"
      },
]