[
  {
    chapter: 11,
    verse: 1,
    word: 1,
    hebrew: "אַ֥בְן",
    english: "A false",
    strongs: "H68",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse: 1,
    word: 2,
    hebrew: "וָאֹ֑בֶן",
    english: "balance",
    strongs: "H68",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse: 1,
    word: 3,
    hebrew: "תּוֹעֲבַ֖ת",
    english: "is an abomination",
    strongs: "H8441",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse: 1,
    word: 4,
    hebrew: "לַיהוָ֣ה",
    english: "to Yahweh,",
    strongs: "H3068",
    grammar: "Proper Noun"
  },
  { 
    chapter: 11,
    verse: 1,
    word: 5,
    hebrew: "וְ",
    english: "but",
    strongs: "H9002",
    grammar: "Conjunction"
  },
  {
    chapter: 11,
    verse: 1,
    word: 6,
    hebrew: "מֹאזְנֵ֣י",
    english: "accurate weights",
    strongs: "H3976",
    grammar: "Noun"
  },
  {
    chapter: 11,
    verse: 1,
    word:7 ,
    hebrew: "רְצֹנ֗וֹ",
    english: "are his delight.",
    strongs: "H7522",
    grammar: "Noun"
  },
  {
    chapter: 11,
    verse: 2,
    word: 1,
    hebrew: "בָּ֣א",
    english: "When",
    strongs: "H0935",
    grammar: "Verb"
  },
  { 
    chapter: 11,
    verse: 2,
    word: 2,
    hebrew: "גַאֲוָ֑ה",
    english: "pride",
    strongs: "H1347",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse: 2,
    word: 3,
    hebrew: "וּ",
    english: "comes,",
    strongs: "H9002",
    grammar: "Conjunction"
  },
  { 
    chapter: 11,
    verse: 2,
    word: 4,
    hebrew: "בָּ֣א",
    english: "then comes",
    strongs: "H0935",
    grammar: "Verb"
  },
  { 
    chapter: 11,
    verse: 2,
    word: 5,
    hebrew: "קָל֗וֹן",
    english: "shame,",
    strongs: "H7036",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse: 2,
    word: 6,
    hebrew: "וּ",
    english: "but",
    strongs: "H9002",
    grammar: "Conjunction"
  },
  { 
    chapter: 11,
    verse: 2,
    word: 7,
    hebrew: "אֶת־",
    english: "with",
    strongs: "H854",
    grammar: "Preposition"
  },
  { 
    chapter: 11,
    verse: 2,
    word: 8,
    hebrew: "עֲנָוָ֖ה",
    english: "humility",
    strongs: "H6038",
    grammar: "Noun"
  },
  {
    chapter: 11,
    verse: 2,
    word: 9,
    hebrew: "חָכְמָ֣ה",
    english: "comes wisdom.",
    strongs: "H2451",
    grammar: "Noun"
  },
  {
    chapter: 11,
    verse: 3,
    word: 1,
    hebrew: "תֻם",
    english: "The integrity",
    strongs: "H8537",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse: 3,
    word: 2,
    hebrew: "יְנַחֵ֣ם",
    english: "of the upright",
    strongs: "H5148",
    grammar: "Adjective"
  },
  { 
    chapter: 11,
    verse: 3,
    word: 3,
    hebrew: "דַּרְכּ֔וֹ",
    english: "shall guide them,",
    strongs: "H1870",
    grammar: "Noun"
  },
  {chapter: 11,
    verse: 3,
    word: 4,
    hebrew: "וּ",
    english: "but",
    strongs: "H9002",
    grammar: "Conjunction"
  },
  {chapter: 11,
    verse: 3,
    word: 5,
    hebrew: "עִקְּשׁוּת֙",
    english: "the perverseness",
    strongs: "H6128",
    grammar: "Noun"
  },
  {chapter: 11,
    verse: 3,
    word: 6,
    hebrew: "בֹגְדִ֣ים",
    english: "of the treacherous",
    strongs: "H898",
    grammar: "Adjective"
  },
  {
    chapter: 11,
    verse: 3,
    word: 7,
    hebrew: "תַּשְׁמִידֵֽם׃",
    english: "shall destroy them.",
    strongs: "H7843",
    grammar: "Verb"
  },
  {
    chapter: 11,
    verse: 4,
    word:1 ,
    hebrew: "עֹֽשֶׁר",
    english: "Riches",
    strongs: "H6239",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse: 4,
    word: 2,
    hebrew: "לֹֽא־",
    english: "don’t",
    strongs: "H3808",
    grammar: "Adverb"
  },
  { 
    chapter: 11,
    verse: 4,
    word: 3,
    hebrew: "יוֹעִ֥ילוּ",
    english: "profit",
    strongs: "H3276",
    grammar: "Verb"
  },
  { 
    chapter: 11,
    verse: 4,
    word:4 ,
    hebrew: "בְי֖וֹם",
    english: "in the day",
    strongs: "H3117",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse: 4,
    word:5 ,
    hebrew: "עֶ֣בְרָה",
    english: "of wrath,",
    strongs: "H5678",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse: 4,
    word: 6,
    hebrew: "וּ",
    english: "but",
    strongs: "H9002",
    grammar: "Conjunction"
  },
  { 
    chapter: 11,
    verse: 4,
    word: 7,
    hebrew: "צְדָקָ֖ה",
    english: "righteousness",
    strongs: "H6666",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse: 4,
    word: 8,
    hebrew: "תַּצִּ֣יל",
    english: "delivers",
    strongs: "H5337",
    grammar: "Verb"
  },
  {
    chapter: 11,
    verse: 4,
    word: 9,
    hebrew: "מִמָּֽוֶת׃",
    english: "from death.",
    strongs: "H4194",
    grammar: "Noun"
  },
  {
    chapter: 11,
    verse:5 ,
    word: 1 ,
    hebrew: "דַּ֣רְכֵי",
    english: "The ways of",
    strongs: "H1870",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse:5 ,
    word:  2,
    hebrew: "צַדִּיקִ֣ים",
    english: "the blameless",
    strongs: "H6662",
    grammar: "Adjective"
  },
  { 
    chapter: 11,
    verse:5 ,
    word:3  ,
    hebrew: "יַשְׁרִ֑ים",
    english: "will direct his way,",
    strongs: "H3477",
    grammar: "Adjective"
  },
  { 
    chapter: 11,
    verse:5 ,
    word: 4 ,
    hebrew: "וְ",
    english: "but",
    strongs: "H9002",
    grammar: "Conjunction"
  },
  { 
    chapter: 11,
    verse:5 ,
    word:  5,
    hebrew: "בֹ֖ושֶׁת",
    english: "the wicked",
    strongs: "H7563",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse:5 ,
    word: 6 ,
    hebrew: "יִפֹּ֣ל",
    english: "shall fall",
    strongs: "H5307",
    grammar: "Verb"
  },
  {
    chapter: 11,
    verse: 5,
    word: 7,
    hebrew: "בְּ֝רָעֹתֹ֗ו",
    english: "by his own wickedness.",
    strongs: "H7451",
    grammar: "Noun"
  },
  {
    chapter: 11,
    verse: 6,
    word: 1 ,
    hebrew: "צִדְקַ֣ת",
    english: "The righteousness",
    strongs: "H6666",
    grammar: "Noun"
  },
  { 
    chapter: 11,
    verse: 6,
    word: 2,
    hebrew: "יְשָׁרִ֣ים",
    english: "of the upright",
    strongs: "H3477",
    grammar: "Adjective"
  },
  {chapter: 11,
    verse: 6,
    word:3 ,
    hebrew: "תַּצִּילֵ֑ם",
    english: "shall deliver them,",
    strongs: "H5337",
    grammar: "Verb"
  },
  {chapter: 11,
    verse: 6,
    word:4 ,
    hebrew: "וּ",
    english: "but",
    strongs: "H9002",
    grammar: "Conjunction"
  },
  {chapter: 11,
    verse: 6,
    word:5 ,
    hebrew: "בְּ",
    english: "the unfaithful",
    strongs: "H898",
    grammar: "Preposition"
  },
  {chapter: 11,
    verse: 6,
    word: 6,
    hebrew: "אֹֽון",
    english: "will be trapped",
    strongs: "H205",
    grammar: "Noun"
  },
  {
    chapter: 11,
    verse: 6,
    word: 7,
    hebrew: "תַּפִּ֥ילֵם",
    english: "by evil desires.",
    strongs: "H5307",
    grammar: "Verb"
  },
  {
    chapter: 11,
    verse: 7,
    word: 1 ,
    hebrew: "בְּ",
    english: "When",
    strongs: "H9002 + H7934",
    grammar: "Preposition"
  },
  {chapter: 11,
    verse: 7,
    word:  2,
    hebrew: "מ֣וֹת",
    english: "a wicked man dies,",
    strongs: "H4194",
    grammar: "Noun"
  },
  {chapter: 11,
    verse: 7,
    word: 3 ,
    hebrew: "תֹּאבֵ֑ד",
    english: "hope perishes,",
    strongs: "H6",
    grammar: "Verb"
  },
  {chapter: 11,
    verse: 7,
    word: 4 ,
    hebrew: "וְ",
    english: "and",
    strongs: "H9002",
    grammar: "Conjunction"
  },
  {chapter: 11,
    verse: 7,
    word:5  ,
    hebrew: "תִקְוַ֥ת",
    english: "expectation",
    strongs: "H8615",
    grammar: "Noun"
  },
  {chapter: 11,
    verse: 7,
    word:  6,
    hebrew: "חָֽזוּקָ֖ה",
    english: "of power",
    strongs: "H2389",
    grammar: "Adjective"
  },
  {
    chapter: 11,
    verse: 7,
    word: 7,
    hebrew: "אָ֣בַד",
    english: "comes to nothing.",
    strongs: "H6",
    grammar: "Verb"
  },
  {
    chapter: 11,
    verse: 8,
    word:  1,
    hebrew: "צַ֭דִּיק",
    english: "A righteous person",
    strongs: "H6662",
    grammar: "Adjective"
  },
  {chapter: 11,
    verse: 8,
    word:2  ,
    hebrew: "מִצָּ֣רָה",
    english: "is delivered",
    strongs: "H6862",
    grammar: "Preposition + Noun"
  },
  {chapter: 11,
    verse: 8,
    word: 3 ,
    hebrew: "וּ",
    english: "and",
    strongs: "H9002",
    grammar: "Conjunction"
  },
  {chapter: 11,
    verse: 8,
    word: 4 ,
    hebrew: "יִבָּא",
    english: "the wicked",
    strongs: "H935",
    grammar: "Verb"
  },
  {
    chapter: 11,
    verse: 8,
    word: 5,
    hebrew: "תַחְתָּ֑יו",
    english: "takes his place.",
    strongs: "H8478",
    grammar: "Preposition + Pronoun"
  },
  {
    chapter: 11,
    verse: 9,
    word: 1 ,
    hebrew: "בְּפִ֣י",
    english: "With his mouth",
    strongs: "H6310",
    grammar: "Preposition + Noun"
  },
  {chapter: 11,
    verse: 9,
    word:  2,
    hebrew: "אֱ֭לִיל",
    english: "the godless man",
    strongs: "H457",
    grammar: "Adjective"
  },
  {chapter: 11,
    verse: 9,
    word: 3 ,
    hebrew: "יְֽשַׁחֵ֣ת",
    english: "destroys",
    strongs: "H7843",
    grammar: "Verb"
  },
  {chapter: 11,
    verse: 9,
    word:  4,
    hebrew: "רֵעֵ֑הוּ",
    english: "his neighbor,",
    strongs: "H7453",
    grammar: "Noun"
  },
  {chapter: 11,
    verse: 9,
    word: 5 ,
    hebrew: "וּ",
    english: "but",
    strongs: "H9002",
    grammar: "Conjunction"
  },
  {chapter: 11,
    verse: 9,
    word: 6 ,
    hebrew: "בְּ",
    english: "the righteous",
    strongs: "H6662",
    grammar: "Preposition"
  },
  {chapter: 11,
    verse: 9,
    word:7  ,
    hebrew: "דַּֽעַת־",
    english: "will be delivered",
    strongs: "H1847",
    grammar: "Noun"
  },
  {
    chapter: 11,
    verse: 9,
    word: 8,
    hebrew: "יְצֻלָּ֥ץ",
    english: "through knowledge.",
    strongs: "H5337",
    grammar: "Verb"
  },

{
chapter: 11,
verse: 10,
word: 1,
hebrew: "כִּֽי־",
english: "When",
strongs: "H3588",
grammar: "Conjunction"
},
{chapter: 11,
verse: 10,
word:2 ,
hebrew: "יִיטַ֣ב",
english: "it goes well with",
strongs: "H3190",
grammar: "Verb"
},
{chapter: 11,
verse: 10,
word: 3,
hebrew: "לַצַּדִּ֑יק",
english: "the righteous",
strongs: "H6662",
grammar: "Adjective"
},
{chapter: 11,
verse: 10,
word: 4,
hebrew: "עִ֝֗יר",
english: "the city",
strongs: "H5892",
grammar: "Noun"
},
{chapter: 11,
verse: 10,
word: 5,
hebrew: "יִשְׂמַ֥ח",
english: "rejoices",
strongs: "H8055",
grammar: "Verb"
},
{chapter: 11,
verse: 10,
word: 6,
hebrew: "כְּשֹׁ֤ד",
english: "When",
strongs: "H3588",
grammar: "Conjunction"
},
{chapter: 11,
verse: 10,
word: 7  ,
hebrew: "אֱוִילִ֨ים",
english: "the wicked",
strongs: "H191",
grammar: "Adjective"
},
{chapter: 11,
verse: 10,
word: 8,
hebrew: "נִאָ֗בֵּד",
english: "perish",
strongs: "H6",
grammar: "Verb"
},
{
chapter: 11,
verse: 10,
word:9 ,
hebrew: "תְּרוּעָֽה׃",
english: "there is shouting.",
Strong: "H8643",
grammar: "Noun"
},
{
chapter: 11,
verse: 11,
word: 1,
hebrew: "בִּבְרָכַ֖ת",
english: "By the blessing of",
strongs: "H1293",
grammar: "Preposition"
},
{chapter: 11,
verse: 11,
word:2 ,
hebrew: "יְשָׁרִ֥ים",
english: "the upright",
strongs: "H3477",
grammar: "Adjective"
},
{chapter: 11,
verse: 11,
word:3 ,
hebrew: "תְּרוּמָ֑ם",
english: "the city",
strongs: "H7311",
grammar: "Noun"
},
{chapter: 11,
verse: 11,
word:4 ,
hebrew: "יָר֣וּם",
english: "is exalted,",
strongs: "H7311",
grammar: "Verb"
},
{chapter: 11,
verse: 11,
word:5 ,
hebrew: "וּבְפִ֖י",
english: "but it is overthrown by the mouth of",
strongs: "H6310",
grammar: "Conjunction, Noun"
},
{
chapter: 11,
verse: 11,
word:6 ,
hebrew: "רְשָׁעִ֣ים",
english: "the wicked.",
strongs: "H7563",
grammar: "Adjective"
},
{
chapter: 11,
verse:12 ,
word:1  ,
hebrew: "אַ֭דְמַת־",
english: "One who",
strongs: "H120",
grammar: "Article, Noun"
},
{chapter: 11,
verse:12 ,
word:  2,
hebrew: "יָעִ֣יר",
english: "despises",
strongs: "H5782",
grammar: "Verb"
},
{chapter: 11,
verse:12 ,
word: 3 ,
hebrew: "רֵעֵ֑הוּ",
english: "his neighbor",
strongs: "H7453",
grammar: "Noun"
},
{chapter: 11,
verse:12 ,
word:4  ,
hebrew: "חָסֶ֥ר",
english: "is void of",
strongs: "H2638",
grammar: "Verb"
},
{chapter: 11,
verse:12 ,
word: 5 ,
hebrew: "לֵ֝֗ב",
english: "wisdom,",
strongs: "H3820",
grammar: "Noun"
},
{chapter: 11,
verse:12 ,
word:6  ,
hebrew: "וְאִ֣ישׁ",
english: "but a man of",
strongs: "H376",
grammar: "Conjunction, Noun"
},
{chapter: 11,
verse:12 ,
word:  7,
hebrew: "תְּבוּנָֽה׃",
english: "understanding",
strongs: "H8394",
grammar: "Noun"
},
{
chapter: 11,
verse: 12,
word: 8,
hebrew: "יַחֲרִ֣ישׁ",
english: "holds his peace.",
strongs: "H2790",
grammar: "Verb"
},
{
chapter: 11,
verse: 13,
word: 1 ,
hebrew: "נֹ֥שֵׂא",
english: "One who",
strongs: "H5375",
grammar: "Verb"
},
{chapter: 11,
verse: 13,
word: 2 ,
hebrew: "רָכִ֖יל",
english: "brings gossip",
strongs: "H7400",
grammar: "Adjective"
},
{chapter: 11,
verse: 13,
word:3  ,
hebrew: "גֹּ֣לֶה",
english: "betrays",
strongs: "H1540",
grammar: "Verb"
},
{chapter: 11,
verse: 13,
word: 4 ,
hebrew: "ס֥וֹד",
english: "a confidence,",
strongs: "H5475",
grammar: "Noun"
},
{chapter: 11,
verse: 13,
word: 5 ,
hebrew: "וְאֶ֣ת",
english: "but one who is of",
strongs: "H853",
grammar: "Conjunction, Preposition"
},
{chapter: 11,
verse: 13,
word: 6 ,
hebrew: "ר֣וּחַ",
english: "a trustworthy",
strongs: "H7307",
grammar: "Noun"
},
{chapter: 11,
verse: 13,
word: 7 ,
hebrew: "אֱמוּנָ֑ה",
english: "spirit",
strongs: "H529",
grammar: "Noun"
},
{chapter: 11,
verse: 13,
word: 8 ,
hebrew: "שׁוֹמֵ֥ר",
english: "is one who keeps",
strongs: "H8104",
grammar: "Verb"
},
{
chapter: 11,
verse: 13,
word: 9,
hebrew: "ס֑וֹד׃",
english: "a secret.",
strongs: "H5475",
grammar: "Noun"
},
{
chapter: 11,
verse: 14,
word:  1,
hebrew: "אֵֽין־",
english: "Where there is no",
strongs: "H369",
grammar: "Conjunction"
},
{chapter: 11,
verse: 14,
word:2  ,
hebrew: "תַּחְבֻּל֣וֹת",
english: "wise guidance,",
strongs: "H8458",
grammar: "Noun"
},
{chapter: 11,
verse: 14,
word:3  ,
hebrew: "יִפֹּ֑ל",
english: "the nation falls,",
strongs: "H5307",
grammar: "Verb"
},
{chapter: 11,
verse: 14,
word: 4 ,
hebrew: "וּ֝בְרֹ֗וב",
english: "but in the multitude of",
strongs: "H7230",
grammar: "Conjunction, Noun"
},
{chapter: 11,
verse: 14,
word:5  ,
hebrew: "יוֹעֵ֥ץ",
english: "counselors",
strongs: "H3289",
grammar: "Noun"
},
{chapter: 11,
verse: 14,
word:  6,
hebrew: "יִֽהְיֶה־",
english: "there is",
strongs: "H1961",
grammar: "Verb"
},
{
chapter: 11,
verse: 14,
word:7 ,
hebrew: "תֹּשַׁ֖ע",
english: "victory.",
strongs: "H8668",
grammar: "Noun"
},
{
chapter: 11,
verse: 15,
word: 1 ,
hebrew: "עָר֥וּב",
english: "He who is collateral",
strongs: "H6161",
grammar: "Verb"
},
{chapter: 11,
verse: 15,
word:2  ,
hebrew: "לְזָר־",
english: "for a stranger",
strongs: "H2114",
grammar: "Preposition, Noun"
},
{chapter: 11,
verse: 15,
word: 3 ,
hebrew: "יֵ֝עָנֶ֗ה",
english: "will suffer for it,",
strongs: "H6030",
grammar: "Verb"
},
{chapter: 11,
verse: 15,
word: 4 ,
hebrew: "וְאֹ֣הֵּל",
english: "but he who refuses pledges of collateral",
strongs: "H408",
grammar: "Conjunction, Verb"
},
{
chapter: 11,
verse: 15,
word: 5,
hebrew: "מִבְטַח־",
english: "is secure.",
strongs: "H4009",
grammar: "Noun"
},
{
chapter: 11,
verse: 16,
word: 1 ,
hebrew: "אִשָּׁ֥ה",
english: "A gracious woman",
strongs: "H802",
grammar: "Noun"
},
{chapter: 11,
verse: 16,
word: 2 ,
hebrew: "חַֽיִל־",
english: "obtains honor,",
strongs: "H2428",
grammar: "Noun"
},
{chapter: 11,
verse: 16,
word:  3,
hebrew: "וְ֝אַנְשֵׁי־",
english: "but violent men",
strongs: "H376",
grammar: "Conjunction, Noun"
},
{
chapter: 11,
verse: 16,
word: 4,
hebrew: "רְֽעִים־",
english: "obtain riches.",
strongs: "H7326",
grammar: "Verb"
},

{
chapter: 11,
verse: 17,
word: 1,
hebrew: "אִ֥ישׁ",
english: "The merciful man",
strongs: "H376",
grammar: "Noun"
},
{chapter: 11,
verse: 17,
word: 2,
hebrew: "חָסִ֖יד",
english: "does good",
strongs: "H2623",
grammar: "Adjective"
},
{chapter: 11,
verse: 17,
word:3 ,
hebrew: "לְֽנַפְשֹׁ֑ו",
english: "to his own soul,",
strongs: "H5315",
grammar: "Preposition, Noun"
},
{chapter: 11,
verse: 17,
word:4 ,
hebrew: "וְאִ֣ישׁ",
english: "but he who is cruel",
strongs: "H376",
grammar: "Conjunction, Noun"
},
{chapter: 11,
verse: 17,
word:5 ,
hebrew: "עָכְר֗וֹ",
english: "troubles",
strongs: "H5916",
grammar: "Verb"
},
{
chapter: 11,
verse:17 ,
word: 6,
hebrew: "בְּשָׂרֹֽו׃",
english: "his own flesh.",
strongs: "H1320",
grammar: "Noun"
},
{
chapter: 11,
verse:18 ,
word: 1,
hebrew: "עָכְרִים֙",
english: "Wicked people",
strongs: "H5916",
grammar: "Adjective"
},
{chapter: 11,
verse:18 ,
word:2 ,
hebrew: "קֹ֤בְצֵי",
english: "earn",
strongs: "H6908",
grammar: "Verb"
},
{chapter: 11,
verse:18 ,
word: 3,
hebrew: "שָׁ֨קֶר",
english: "deceitful",
strongs: "H8267",
grammar: "Adjective"
},
{chapter: 11,
verse:18 ,
word: 4,
hebrew: "פְעֻלָּ֗ה",
english: "wages,",
strongs: "H6468",
grammar: "Noun"
},
{chapter: 11,
verse:18 ,
word:5 ,
hebrew: "וְזֹרֵ֚עַ",
english: "but one who sows",
strongs: "H2232",
grammar: "Conjunction, Verb"
},
{chapter: 11,
verse:18 ,
word:6 ,
hebrew: "צְדָקָ֔ה",
english: "righteousness",
strongs: "H6666",
grammar: "Noun"
},
{chapter: 11,
verse:18 ,
word: 7,
hebrew: "שָׂכֹ֖ר",
english: "reaps",
strongs: "H7936",
grammar: "Verb"
},
{
chapter: 11,
verse: 18,
word:8 ,
hebrew: "אֱֽמוּנָֽה׃",
english: "a sure reward.",
strongs: "H529",
grammar: "Noun"
},
{
chapter: 11,
verse: 19,
word: 1,
hebrew: "צַֽדִּ֥יק",
english: "He who is truly righteous",
strongs: "H6662",
grammar: "Adjective"
},
{chapter: 11,
verse: 19,
word: 2,
hebrew: "בְּ֝חַיִּ֗ים",
english: "gets life.",
strongs: "H2416",
grammar: "Noun"
},
{chapter: 11,
verse: 19,
word:3 ,
hebrew: "וְרֹדֶ֥ף",
english: "He who pursues",
strongs: "H7291",
grammar: "Conjunction, Verb"
},
{chapter: 11,
verse: 19,
word:4 ,
hebrew: "רָ֑ע",
english: "evil",
strongs: "H7451",
grammar: "Adjective"
},
{
chapter: 11,
verse: 19,
word:5 ,
hebrew: "מָ֝֗וֶת",
english: "gets death.",
strongs: "H4194",
grammar: "Noun"
},
{
chapter: 11,
verse: 20,
word:  1,
hebrew: "עִקֵּ֣שֵׁי",
english: "Those who are perverse",
strongs: "H6121",
grammar: "Adjective"
},
{chapter: 11,
verse: 20,
word:2  ,
hebrew: "לֵ֣ב",
english: "in heart",
strongs: "H3820",
grammar: "Noun"
},
{chapter: 11,
verse: 20,
word:3  ,
hebrew: "תּוֹעֲבַ֣ת",
english: "are an abomination",
strongs: "H8441",
grammar: "Noun"
},
{chapter: 11,
verse: 20,
word:4  ,
hebrew: "לַיהוָ֑ה",
english: "to Yahweh,",
strongs: "H3068",
grammar: "Preposition"
},
{chapter: 11,
verse: 20,
word: 5 ,
hebrew: "וּ֝מְתֵימֵי־",
english: "but those whose ways are blameless",
strongs: "H853",
grammar: "Conjunction, Adjective"
},
{
chapter: 11,
verse: 20,
word:6 ,
hebrew: "דְרָכָ֗יו",
english: "are his delight.",
strongs: "H1870",
grammar: "Noun"
},
{
chapter: 11,
verse: 21,
word:1 ,
hebrew: "כִּֽי־",
english: "Most certainly,",
strongs: "H3588",
grammar: "Conjunction"
},
{chapter: 11,
verse: 21,
word: 2,
hebrew: "לֹ֥א",
english: "the evil man",
strongs: "H3808",
grammar: "Adverb"
},
{chapter: 11,
verse: 21,
word:3 ,
hebrew: "יִנָּקֶ֑ה",
english: "will not be unpunished,",
strongs: "H5352",
grammar: "Verb"
},
{chapter: 11,
verse: 21,
word:4 ,
hebrew: "וְֽזֶרַע",
english: "but the offspring of",
strongs: "H2233",
grammar: "Conjunction, Noun"
},
{chapter: 11,
verse: 21,
word: 5,
hebrew: "צַדִּיקִ֥ים",
english: "the righteous",
strongs: "H6662",
grammar: "Adjective"
},
{
chapter: 11,
verse: 21,
word:6 ,
hebrew: "יִמָּלֵֽט׃",
english: "will be delivered.",
strongs: "H4422",
grammar: "Verb"
},
{
chapter: 11,
verse: 22,
word:  1,
hebrew: "זָֽהָב",
english: "Like a gold",
strongs: "H2091",
grammar: "Noun"
},
{chapter: 11,
verse: 22,
word: 2 ,
hebrew: "בְּאַף־",
english: "ring in a pig's snout,",
strongs: "H639",
grammar: "Preposition, Noun"
},
{chapter: 11,
verse: 22,
word:3  ,
hebrew: "אִשָּׁ֖ה",
english: "is a beautiful woman",
strongs: "H802",
grammar: "Noun"
},
{
chapter: 11,
verse: 22,
word:4 ,
hebrew: "הֲדַר־",
english: "who lacks discretion.",
strongs: "H1926",
grammar: "Adjective"
},
{
chapter: 11,
verse: 23,
word: 1,
hebrew: "תַּ֭אֲוַת",
english: "The desire of",
strongs: "H8378",
grammar: "Noun"
},
{chapter: 11,
verse: 23,
word: 2,
hebrew: "צַדִּיקִ֑ים",
english: "the righteous",
strongs: "H6662",
grammar: "Adjective"
},
{chapter: 11,
verse: 23,
word: 3,
hebrew: "אַ֥ךְ",
english: "is only",
strongs: "H389",
grammar: "Adverb"
},
{chapter: 11,
verse: 23,
word: 4,
hebrew: "טֹ֝֗וב",
english: "good.",
strongs: "H2896",
grammar: "Adjective"
},
{chapter: 11,
verse: 23,
word: 5,
hebrew: "תִּקְוַ֣ת",
english: "The expectation of",
strongs: "H8615",
grammar: "Noun"
},
{chapter: 11,
verse: 23,
word: 6,
hebrew: "רְשָׁעִ֥ים",
english: "the wicked",
strongs: "H7563",
grammar: "Adjective"
},
{
chapter: 11,
verse: 23,
word: 7,
hebrew: "חֵ֗מָה",
english: "is wrath.",
strongs: "H2534",
grammar: "Noun"
},
{
chapter: 11,
verse: 24,
word:1 ,
hebrew: "יֵ֥שׁ",
english: "There is one who",
strongs: "H3426",
grammar: "Verb"
},
{chapter: 11,
verse: 24,
word: 2,
hebrew: "זֹורֵ֑עַ",
english: "scatters,",
strongs: "H2232",
grammar: "Verb"
},
{chapter: 11,
verse: 24,
word:3 ,
hebrew: "וְ֝יֹסֵ֗ף",
english: "and increases",
strongs: "H3254",
grammar: "Conjunction, Verb"
},
{chapter: 11,
verse: 24,
word: 4,
hebrew: "עֹ֥וד",
english: "yet more.",
strongs: "H5750",
grammar: "Adverb"
},
{chapter: 11,
verse: 24,
word: 5,
hebrew: "וְיֵ֣שׁ",
english: "There is one who",
strongs: "H3426",
grammar: "Verb"
},
{chapter: 11,
verse: 24,
word: 6,
hebrew: "מַחְסֹ֣ר",
english: "withholds",
strongs: "H2638",
grammar: "Verb"
},
{chapter: 11,
verse: 24,
word: 7,
hebrew: "מֵאֱפֹ֣ס",
english: "more than is appropriate,",
strongs: "H6485",
grammar: "Preposition, Noun"
},
{chapter: 11,
verse: 24,
word: 8,
hebrew: "וּ֝מֵרַב־",
english: "but gains",
strongs: "H7235",
grammar: "Conjunction, Noun"
},
{
chapter: 11,
verse: 24,
word:9 ,
hebrew: "וּמִדְלִ֗ים",
english: "poverty.",
strongs: "H7389",
grammar: "Noun"
},
{
chapter: 11,
verse: 25,
word:  1,
hebrew: "נֶ֣פֶשׁ",
english: "The liberal soul",
strongs: "H5315",
grammar: "Noun"
},
{
  chapter: 11,
  verse: 25,
  word:  2,
  hebrew: "מְרַעֲבָ֑ה",
  english: "shall be made fat.",
  strongs: "H7326",
  grammar: "Verb"
},
{chapter: 11,
verse: 25,
word:3  ,
hebrew: "וְהַֽמַּשְׁקֶ֖ה",
english: "He who waters",
strongs: "H8248",
grammar: "Conjunction, Verb"
},
{chapter: 11,
verse: 25,
word: 4 ,
hebrew: "יַֽשְׁקֶ֥ה",
english: "shall be watered",
strongs: "H8248",
grammar: "Verb"
},
{
chapter: 11,
verse: 25,
word:5 ,
hebrew: "גַּם־",
english: "also himself.",
strongs: "H1571",
grammar: "Adverb"
},

{
chapter: 11,
verse:26 ,
word:  1,
hebrew: "אָ֭רוּר",
english: "People curse",
strongs: "H779",
grammar: "Verb"
},
{chapter: 11,
verse:26 ,
word:  2,
hebrew: "מְעַלֵּ֣ה",
english: "someone who withholds",
strongs: "H6113",
grammar: "Noun"
},
{chapter: 11,
verse:26 ,
word: 3 ,
hebrew: "דָגָ֑ן",
english: "grain,",
strongs: "H1715",
grammar: "Noun"
},
{chapter: 11,
verse:26 ,
word: 4 ,
hebrew: "וּֽבְרָכָ֖ה",
english: "but blessing",
strongs: "H1293",
grammar: "Conjunction, Noun"
},
{chapter: 11,
verse:26 ,
word: 5 ,
hebrew: "עַל־",
english: "will be on",
strongs: "H5921",
grammar: "Preposition"
},
{chapter: 11,
verse:26 ,
word:6  ,
hebrew: "רֹ֣אשׁ",
english: "the head of",
strongs: "H7218",
grammar: "Noun"
},
{
chapter: 11,
verse: 26,
word: 7,
hebrew: "מֹ֭כְרֹ֥ו",
english: "him who sells it.",
strongs: "H4376",
grammar: "Verb"
},
{
chapter: 11,
verse:27 ,
word: 1,
hebrew: "בָּֽקַשׁ",
english: "He who diligently seeks",
strongs: "H1245",
grammar: "Verb"
},
{chapter: 11,
verse:27 ,
word: 2,


hebrew: "טֹ֑וב",
english: "good",
strongs: "H2896",
grammar: "Adjective"
},
{chapter: 11,
verse:27 ,
word: 3,
hebrew: "יְבַקֶּשׁ־",
english: "seeks favor,",
strongs: "H1245",
grammar: "Verb"
},
{chapter: 11,
verse:27 ,
word: 4,
hebrew: "וְחֹ֥קֵר",
english: "but he who searches after",
strongs: "H2713",
grammar: "Conjunction, Verb"
},
{chapter: 11,
verse:27 ,
word: 5,
hebrew: "רָ֝עָ֗ה",
english: "evil,",
strongs: "H7451",
grammar: "Adjective"
},
{
chapter: 11,
verse: 27,
word:6 ,
hebrew: "תָּבֹ֥וא",
english: "it shall come to him.",
strongs: "H935",
grammar: "Verb"
},
{
chapter: 11,
verse: 28,
word: 1 ,
hebrew: "הַבֹּ֣וטֵֽחַ",
english: "He who trusts in",
strongs: "H982",
grammar: "Article, Verb"
},
{chapter: 11,
verse: 28,
word:  2,
hebrew: "בְּעֹשְׁרֹ֣ו",
english: "his riches",
strongs: "H6239",
grammar: "Noun"
},
{chapter: 11,
verse: 28,
word: 3 ,
hebrew: "יִ֭פֹּל",
english: "will fall,",
strongs: "H5307",
grammar: "Verb"
},
{chapter: 11,
verse: 28,
word: 4 ,
hebrew: "וְצַדִּיקִ֥ים",
english: "but the righteous",
strongs: "H6662",
grammar: "Conjunction, Adjective"
},
{chapter: 11,
verse: 28,
word:5  ,

hebrew: "כְּעָלֶ֥ה",
english: "shall flourish as the green",
strongs: "H5929",
grammar: "Preposition, Noun"
},
{
chapter: 11,
verse:28 ,
word:6 ,
hebrew: "רָֽעֲנָ֗ן׃",
english: "leaf.",
strongs: "H7488",
grammar: "Adjective"
},
{
chapter: 11,
verse:29 ,
word: 1,
hebrew: "עֹ֭כֵר",
english: "He who troubles",
strongs: "H5916",
grammar: "Verb"
},
{chapter: 11,
verse:29 ,
word:2  ,
hebrew: "בֵּיתֹ֑ו",
english: "his own house",
strongs: "H1004",
grammar: "Noun"
},
{chapter: 11,
verse:29 ,
word: 3 ,
hebrew: "יִירַ֖שׁ",
english: "shall inherit",
strongs: "H3423",
grammar: "Verb"
},
{chapter: 11,
verse:29 ,
word: 4 ,
hebrew: "רֽוּחַ׃",
english: "the wind.",
strongs: "H7307",
grammar: "Noun"
},
{chapter: 11,
verse:29 ,
word: 5 ,
hebrew: "אֱוִ֤יל",
english: "The foolish",
strongs: "H191",
grammar: "Adjective"
},
{chapter: 11,
verse:29 ,
word:6  ,
hebrew: "יִ֭הְיֶה",
english: "shall be",
strongs: "H1961",
grammar: "Verb"
},
{chapter: 11,
verse:29 ,
word: 7 ,
hebrew: "לַֽעֲבֵ֣ד",
english: "servant to",
strongs: "H5650",
grammar: "Noun"
},
{chapter: 11,
verse:29 ,
word:8  ,
hebrew: "לְֽחָכְמֵי־",
english: "the wise",
strongs: "H2450",
grammar: "Preposition, Adjective"
},
{
  chapter: 11,
  verse: 29,
  word: 9,
  hebrew: "לֵ֣ב",
  english: "of heart.",
  strongs: "H3820",
  grammar: "Noun"
},
{
  chapter: 11,
  verse: 30,
  word:  1,
  hebrew: "פְּרִ֣י",
  english: "The fruit of",
  strongs: "H6529",
  grammar: "Noun"
},
{ 
  chapter: 11,
  verse: 30,
  word: 2 ,
  hebrew: "צַדִּיקִ֑ים",
  english: "the righteous",
  strongs: "H6662",
  grammar: "Adjective"
},
{
  chapter: 11,
  verse: 30,
  word: 3 ,
  hebrew: "עֵֽץ־",
  english: "is a tree of",
  strongs: "H6086",
  grammar: "Noun"
},
{
  chapter: 11,
  verse: 30,
  word:4  ,
  hebrew: "חַיִּ֑ים",
  english: "life.",
  strongs: "H2416",
  grammar: "Noun"
},
{ 
  chapter: 11,
  verse: 30,
  word:  5,
  hebrew: "וְֽלֹקֵ֖חַ",
  english: "He who is wise",
  strongs: "H3947",
  grammar: "Conjunction, Verb"
},
{
  chapter: 11,
  verse: 30,
  word:6 ,
  hebrew: "נְפָשֹׁ֣ות",
  english: "wins souls.",
  strongs: "H5315",
  grammar: "Noun"
},
{
  chapter: 11,
  verse:31 ,
  word: 1,
  hebrew: "הֵ֝֗ן",
  english: "Behold,",
  strongs: "H2005",
  grammar: "Interjection"
},
{ 
  chapter: 11,
  verse:31 ,
  word: 2,
  hebrew: "יְֽשַׁלֵּם־",
  english: "the righteous shall be repaid",
  strongs: "H7999",
  grammar: "Verb"
},
{ 
  chapter: 11,
  verse:31 ,
  word: 3,
  hebrew: "בָּאָֽרֶץ׃",
  english: "in the earth,",
  strongs: "H776",
  grammar: "Preposition, Noun"
},
{
  chapter: 11,
  verse:31 ,
  word: 4,
  hebrew: "אַ֭ף",
  english: "how much more",
  strongs: "H637",
  grammar: "Conjunction"
},
{
  chapter: 11,
  verse:31 ,
  word:5 ,
  hebrew: "רָ֥שָׁע",
  english: "the wicked",
  strongs: "H7563",
  grammar: "Adjective"
},
{
  chapter: 11,
  verse:31 ,
  word: 6,
  hebrew: "וְחוֹטֵֽא׃",
  english: "and the sinner",
  strongs: "H2400",
  grammar: "Conjunction, Verb"
},
  
  
]